### ISSUE TITLE
adding a python  `<object>.__repr__()` to Topologic classes that declare GetTypeAsString

### ISSUE THREAD

**Issue by zeffii** [wassimj/topologicPy#12]
https://github.com/wassimj/topologicPy/blob/b64a2679b1bc21efdfb016eef0ec0f1793af7a98/cpython/topologic/include/Shell.h#L167

my C / C++ knowledge is too primitive to be certain this is a useful addition, but here it goes.

can't you add something like
```diff
 virtual std::string GetTypeAsString() const;
+ virtual std::string __repr__() const {return Topology::GetTypeAsString()};
```
allowing
```python
print(some_object) 

#..rather than 
print(some_object.GetTypeAsString())
```
that way Sverchok's Stethoscope (and anyone introspecting the Topologic python API) will print useful info by default.

**Comment by wlav** [comment]
Does it have to be `__repr__` in this case? Doesn't it make more sense to have Stethoscope (with which I'm not familiar, so I may be saying something silly here) use `__str__`? The default behavior for `__str__` is to call `__repr__` anyway, so the reason why `print` works in the example above is b/c of the redirect.

The point being that although modifying C++ classes is sometimes fine, cppyy will actually use C++ string printing (`operator<<(std:ostream&, ...`) for `__str__`, which can be added as a global overload, so independent of access to the C++ class, and C++ will benefit, too.

(The other thing it enables is `operator const char*()` to `__str__`, but `operator std::string()` can't work the same way, so this is not particularly convenient.)

Also, it is of course perfectly possible to add `__str__` or `__repr__` after the fact in Python, e.g. using pythonization callbacks, see: https://cppyy.readthedocs.io/en/latest/pythonizations.html . A pythonization would simply use Python's reflection to look for the presence of `GetTypeAsString` as a method in the class's `__dict__` and if there, map it to `__str__` or `__repr__` as appropriate. As a general rule, it is beneficial to do Python thingies in Python, leaving C++ blissfully unaware.

**Comment by zeffii** [comment]
> As a general rule, it is beneficial to do Python thingies in Python, leaving C++ blissfully unaware.

that's a fair statement

Stethoscope would also like to be blissfully unaware of the objects it's displaying, I may poke around a little in Sverchok with some dummy python objects. If you could do one of those Pythonizations you mentioned I think it would serve us both well.

**Comment by wlav** [comment]
Sure; it could work like the one below. The pythonizations can be kept completely separate from C++ and even in Python live in a separate module. The only thing that is important, is that b/c the pythonizor is a callback, it needs to be installed before any TopologicPy proxy classes are created (or they won't be so pythonized). Pythonizors can be global, or attached to a specific C++ namespace only, as is done here (`TopologicCore`). The latter approach is more efficient and/because better contained. Searching for `GetTypeAsString` in `__dict__` rather than using `hasattr` plays better with inheritance.

```
import cppyy

# minimal code extraction to make this example self-contained
cppyy.cppdef("""\
namespace TopologicCore {

class Shell {
public:
    virtual std::string GetTypeAsString() const {
        return "hi there!";
    }
}; }""")

# below needs to be added to some module imported before creating any proxy classes
def pythonize_topologic_printing(klass, name):
    if 'GetTypeAsString' in klass.__dict__:
        klass.__str__ = lambda self: str(self.GetTypeAsString())

cppyy.py.add_pythonization(pythonize_topologic_printing, 'TopologicCore')

# example usage
s = cppyy.gbl.TopologicCore.Shell()
print(s)
```

**Comment by wassimj** [comment]
Hi @wlav 
I am trying to implement pythonization as you have described and your code, on its own works, but the problem happens once I import topologic in python. It is telling me the class (I am using Vertex as an example) was already defined. I am not sure at what stage I need to insert the pythonization code because as you said, if I run it after the proxy classes are created, it also fails.

```
C:\Users\wassimj\topologicbim\topologicPy\cpython>python
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import topologic
>>> quit()

C:\Users\wassimj\topologicbim\topologicPy\cpython>
C:\Users\wassimj\topologicbim\topologicPy\cpython>python
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
>>> cppyy.cppdef("""\
... namespace TopologicCore {
...
... class Vertex {
... public:
...     virtual std::string GetTypeAsString() const {
...         return "hi I am a Vertex";
...     }
... }; }""")
True
>>>
>>> def pythonize_topologic_printing(klass, name):
...     if 'GetTypeAsString' in klass.__dict__:
...         klass.__str__ = lambda self: str(self.GetTypeAsString())
...
>>> cppyy.py.add_pythonization(pythonize_topologic_printing, 'TopologicCore')
>>>
>>> v = cppyy.gbl.TopologicCore.Vertex()
>>> print(v)
hi I am a Vertex
>>> import topologic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wassimj\topologicbim\topologicPy\cpython\topologic\__init__.py", line 110, in <module>
    cppyy.include(topologic_inc + "/" + header )
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python38\lib\site-packages\cppyy\__init__.py", line 229, in include
    raise ImportError('Failed to load header file "%s"%s' % (header, err.err))
ImportError: Failed to load header file "C:/Users/wassimj/topologicbim/Topologic/TopologicCore/include/Graph.h"
In file included from input_line_49:1:
In file included from C:/Users/wassimj/topologicbim/Topologic/TopologicCore/include/Graph.h:20:
C:/Users/wassimj/topologicbim/Topologic/TopologicCore/include/Vertex.h:45:8: error: redefinition of 'Vertex'
        class Vertex : public Topology
              ^
input_line_19:3:7: note: previous definition is here
class Vertex {
      ^
In file included from input_line_49:1:
C:/Users/wassimj/topologicbim/Topologic/TopologicCore/include/Graph.h:43:61: error: no member named 'Ptr' in
```

**Comment by wlav** [comment]
As per the comments in the example, I added that code to make the example standalone to play with w/o TopologicCore. If you added to Tolopogic, you only need to portion as indicated by the comments. I reproduce the standalone portion here:

```
import cppyy

def pythonize_topologic_printing(klass, name):
    if 'GetTypeAsString' in klass.__dict__:
        klass.__str__ = lambda self: str(self.GetTypeAsString())

cppyy.py.add_pythonization(pythonize_topologic_printing, 'TopologicCore')
```

**Comment by wassimj** [comment]
Thank you @wlav. It is all now working! I have updated the files on github.
![TopologicVertex](https://user-images.githubusercontent.com/6302909/111897766-ac08b780-8a19-11eb-87ad-323dc0ac58dc.PNG)
