### ISSUE TITLE
Windows 10 Install Failure

### ISSUE THREAD

**Issue by JitQL** [wassimj/topologicPy#13]
Hi again Wassim,

I followed every step of your windows install instructions here:

https://github.com/wassimj/topologicPy/blob/master/README-windows.md

But got to an error on step 9:

![image](https://user-images.githubusercontent.com/71294919/111068889-7d8f5780-84c2-11eb-9b98-ac689e45a0b4.png)

If you require more info, just say so.

Thanks in advance,

João

**Comment by JitQL** [comment]
The portuguese message reads: 

> Windows can't find'..\output\x64\Release'. Make sure you wrote it correctly and try again.

**Comment by wassimj** [comment]
nmake is part of Visual Studio 2017. You need to configure it to build C++ projects. https://code.visualstudio.com/docs/cpp/config-msvc

**Comment by JitQL** [comment]
OK, thanks for your help again. I managed to install that and follow a few more steps but I couldn't finalize it.

![topologic install fail again](https://user-images.githubusercontent.com/71294919/111217500-8587ee00-85cd-11eb-9cdd-c1f7a7d483f1.jpg)

**Comment by wassimj** [comment]
I fixed the name of the __init__.py file. It was a typo
In your last screen shot, you simply mis-interpreted the instructions. Sorry they were not clear:
1. Open a Shell window. At the command prompt type the following:
2. cd C:/Users/*homefolder*/topologicbim
3. python example.py

So do NOT type python example.py INSIDE the python system. It is typed outside

**Comment by JitQL** [comment]
Thanks again,

I performed this on windows powershell (admin), but it throws a fatal error:

`PS C:\Users\Joao\Topologicbim\topologicpy\cpython> python setup.py build
running build
running build_py
PS C:\Users\Joao\Topologicbim\topologicpy\cpython> python setup.py install
running install
running bdist_egg
running egg_info
writing topologic.egg-info\PKG-INFO
writing dependency_links to topologic.egg-info\dependency_links.txt
writing requirements to topologic.egg-info\requires.txt
writing top-level names to topologic.egg-info\top_level.txt
reading manifest file 'topologic.egg-info\SOURCES.txt'
writing manifest file 'topologic.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\topologic
copying build\lib\topologic\__init__.py -> build\bdist.win-amd64\egg\topologic
byte-compiling build\bdist.win-amd64\egg\topologic\__init__.py to __init__.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying topologic.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying topologic.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying topologic.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying topologic.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying topologic.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
topologic.__pycache__.__init__.cpython-38: module references __file__
creating 'dist\topologic-0.3-py3.8.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing topologic-0.3-py3.8.egg
removing 'c:\users\joao\appdata\local\programs\python\python38\lib\site-packages\topologic-0.3-py3.8.egg' (and everything under it)
creating c:\users\joao\appdata\local\programs\python\python38\lib\site-packages\topologic-0.3-py3.8.egg
Extracting topologic-0.3-py3.8.egg to c:\users\joao\appdata\local\programs\python\python38\lib\site-packages
topologic 0.3 is already the active version in easy-install.pth

Installed c:\users\joao\appdata\local\programs\python\python38\lib\site-packages\topologic-0.3-py3.8.egg
Processing dependencies for topologic==0.3
Searching for CPyCppyy==1.12.2
Reading https://pypi.org/simple/CPyCppyy/
Downloading https://files.pythonhosted.org/packages/3f/76/0a7048c990892f3f8b2c4536b8e76dc0e41f310239ab5bfc5692a9782ba9/CPyCppyy-1.12.2.tar.gz#sha256=0ac5465cf10acd07d2d57c19e385376a21514eb03e4fa0cbfe3171a3d50df02d
Best match: CPyCppyy 1.12.2
Processing CPyCppyy-1.12.2.tar.gz
Writing C:\Users\Joao\AppData\Local\Temp\easy_install-jgu3hrvq\CPyCppyy-1.12.2\setup.cfg
Running CPyCppyy-1.12.2\setup.py -q bdist_egg --dist-dir C:\Users\Joao\AppData\Local\Temp\easy_install-jgu3hrvq\CPyCppyy-1.12.2\egg-dist-tmp-qcxli7wb
WARNING: The wheel package is not available.
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
API.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CallContext.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
Converters.cxx
src\Converters.cxx(1478): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
src\Converters.cxx(2960): warning C4244: 'argument': conversion from 'dim_t' to 'long', possible loss of data
src\Converters.cxx(3002): warning C4244: 'argument': conversion from 'dim_t' to 'long', possible loss of data
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPClassMethod.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPConstructor.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPDataMember.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPEnum.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPExcInstance.cxx
src\CPPExcInstance.cxx(226): warning C4273: 'CPyCppyy::CPPExcInstance_Type': inconsistent dll linkage
c:\users\joao\appdata\local\temp\easy_install-jgu3hrvq\cpycppyy-1.12.2\src\CPPExcInstance.h(23): note: see previous definition of 'CPPExcInstance_Type'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPFunction.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPGetSetItem.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPInstance.cxx
src\CPPInstance.cxx(892): warning C4273: 'CPyCppyy::CPPInstance_Type': inconsistent dll linkage
c:\users\joao\appdata\local\temp\easy_install-jgu3hrvq\cpycppyy-1.12.2\src\CPPInstance.h(117): note: see previous definition of 'CPPInstance_Type'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPMethod.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPOperator.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPOverload.cxx
src\CPPOverload.cxx(901): warning C4273: 'CPyCppyy::CPPOverload_Type': inconsistent dll linkage
c:\users\joao\appdata\local\temp\easy_install-jgu3hrvq\cpycppyy-1.12.2\src\CPPOverload.h(78): note: see previous definition of 'CPPOverload_Type'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPPScope.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CPyCppyyModule.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
CustomPyTypes.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
Dispatcher.cxx
src\Dispatcher.cxx(52): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
DispatchPtr.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
Executors.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
LowLevelViews.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
MemoryRegulator.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
ProxyWrappers.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
PyException.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
PyResult.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
PyStrings.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
Pythonize.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
TemplateProxy.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
TPyArg.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
TPyClassGenerator.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
TupleOfInstances.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
TypeManip.cxx
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
Utility.cxx
LINK : fatal error LNK1181: cannot open input file 'libcppyy_backend.lib'
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
PS C:\Users\Joao\Topologicbim\topologicpy\cpython>
`


After this, I still see this error, even if I'm in the command prompt of the powershell:

`PS C:\Users\Joao\Topologicbim> python example.py
C:\Users\Joao\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'example.py': [Errno 2] No such file or directory
PS C:\Users\Joao\Topologicbim>
`

**Comment by wassimj** [comment]
How about we do a zoom session to see the issue? Book on http://jabiw.ycb.me

**Comment by JitQL** [comment]
That's very generous of you and would be very good for me, but I'd hate to be would be wasting your time.

If you're sure...

**Comment by wassimj** [comment]
I am closing this issue, but please feel free to re-open if you need more help.
