### ISSUE TITLE
implementing 3d Voronois

### ISSUE THREAD

**Issue by Sinasta** [wassimj/topologicpy#14]
would you be interested in having a three dimensional Voronoi division function? basically the idea is to use a cell and points in that cell as an input and as an output you would have a list of Voronoi cells.
This is not a great [example](https://www.thingiverse.com/thing:5194092) ([code](https://github.com/JustinSDK/cqMore/blob/main/examples/voronoi_cube.py)) but i could not find better for now.
Basically i am using a three dimensional Voronoi in my personal Project in order to achieve a [weighted 2d Voronoi](https://en.wikipedia.org/wiki/Weighted_Voronoi_diagram) through slicing, because [a power diagram in dimension n is only a(n unweighted) Voronoi diagram in dimension n+1](https://stackoverflow.com/a/16027145).
Maybe there are better ways to use [weighted voronoi diagramms](https://gist.github.com/marmakoide/45d5389252683ae09c2df49d0548a627) but i think for an integration in topologicpy it would make sense to implement a 3d (cell level) Voronoi division.
Please let me know what you think and please tell me as well if the amount of issues i open annoys you.
If the latter is true i will stop bothering you.

**Comment by Sinasta** [comment]
If there is a better way to communicate feature proposals then to open Github issues, please let me know.

**Comment by wassimj** [comment]
This is fine, but best to assign an "enhancement" label from the right column so that we can identify them quickly. I just did so so for this post.

**Comment by wassimj** [comment]
Sure! I had done one based on a tutorial in 3ds max many years ago. For this, it would be a CellComplex so:
CellComplex.Voronoi(cell: topologic.Cell, vertices: list, tolerance: float =0.001) -> CellComplex

**Comment by Sinasta** [comment]
Exactly the output would obviously be a CellComplex rather then a list of Cells (my bad). I will have a look into that.
