### ISSUE TITLE
Warning message during installation on Fedora

### ISSUE THREAD

**Issue by paullee0** [wassimj/topologicPy#15]
Following installation instructions discussed in #14 

There is a warning during installation, not sure if it matters or not :D

`make -j3
`

```
...
[ 90%] Building CXX object TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/TopologyUtility.cpp.o
/run/media/paullee/Home/paullee/Documents/topologicbim/Topologic/TopologicCore/src/Utilities/FaceUtility.cpp: In static member function ‘static TopologicCore::Face::Ptr TopologicUtilities::FaceUtility::ByVertices(const >std::__cxx11::list<std::__cxx11::list<std::shared_ptr > >&)’:
/run/media/paullee/Home/paullee/Documents/topologicbim/Topologic/TopologicCore/src/Utilities/FaceUtility.cpp:116:2: warning: control reaches end of non-void function [-Wreturn-type]
116 | }
| ^
[ 92%] Building CXX object TopologicCore/CMakeFiles/TopologicCore.dir/src/Utilities/TransformationMatrix2D.cpp.o

```

**Comment by brunopostle** [comment]
This seems to be related to this code, basically FaceUtility.ByVertices() didn't compile with gcc, so the function doesn't return anything on Linux:

    #ifdef _WIN32
                            Handle(Geom_Surface) pSurface = GeomAPI_PointsToBSplineSurface(occtPoints).Surface();
                            return TopologicCore::Face::BySurface(pSurface);
    #else
                            /* doesn't compile with gcc: error: conversion from ‘handle<Geom_BSplineSurface>’ to non-scalar type ‘handle<Geom_Surface>’ requested
                             */
    #endif

**Comment by wassimj** [comment]
These warnings can be safely ignored if it builds fine at the end.

**Comment by paullee0** [comment]
Thanks for advice :)

**Comment by brunopostle** [comment]
Note, this is a bug in TopologicCore. When I got it to build on Linux I put the part of FaceUtility.ByVertices() that returns a result in an #ifdef.

This #ifdef is still there. i.e. this warning indicates that FaceUtility.ByVertices() doesn't work on Linux

**Comment by wassimj** [comment]
Not 100% sure, but I think I know what this bug is: It is creating a BSpline Surface and the type is specified as a simple Surface. I have to consult the API on how to convert/cast a BSpline surface as a surface. This method is rarely used and is not a main part of core functionality. You can always create edges by vertices, wire by edges and then face by wire.

**Comment by wassimj** [comment]
I am closing this issue, but please feel free to re-open if you need more help.
