### ISSUE TITLE
Install cppyy via pip return error on Fedora 31

### ISSUE THREAD

**Issue by paullee0** [wassimj/topologicPy#16]
Problem reported at  -  [link](https://bitbucket.org/wlav/cppyy/issues/327/pip-install-cppyy-on-fedora31-not-working)

**Comment by paullee0** [comment]
Solution provided on bitbucket seems good :)

**Comment by wassimj** [comment]
Can you link to solution here please? Thanks

**Comment by paullee0** [comment]
Here you  go :)
[Link to bitbucket] (https://bitbucket.org/wlav/cppyy/issues/327/pip-install-cppyy-on-fedora31-not-working)

**Comment by paullee0** [comment]
`export CPPYY_API_PATH=/home/paullee/.local/include/python3.7m`

Latest advice there seems works, however, in my Fedora 31 FreeCAD on AppImage, try import topoloigc still return error

`
import topologic
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'topologic'
`

**Comment by paullee0** [comment]
See [latest discussion](https://bitbucket.org/wlav/cppyy/issues/327/pip-install-cppyy-on-fedora31-not-working#comment-60178144) in which wlav explain some salient point for installation in Fedora.

Hope someone can make sense of all the procedures and make a Fedora / FreeCAD AppImage specific instructions for installation :D

**Comment by wassimj** [comment]
I am closing this issue, but please feel free to re-open if you need more help.
