### ISSUE TITLE
How to convert OCCTShape

### ISSUE THREAD

**Issue by tnakaicode** [wassimj/topologicpy#17]
I am trying to convert Torus created with topologicpy by Topology.ByOCCTShape() and tried to draw it in OpenCASCDAE's Python Warpper called pythonocc-core (https://github.com/tpaviot/pythonocc-core), but I get an Error.
That because type is still topologic.TopoDS_Shape converting by Topology.ByOCCTShape().

Is there any way to solve this problem?

my code is following:

```python

import sys
import os

sys.path.append(os.path.join("./"))
import topologicpy
# import topologic

from topologicpy.Cell import Cell
from topologicpy.Topology import Topology

from OCC.Display.SimpleGui import init_display
from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox

import logging
logging.getLogger('matplotlib').setLevel(logging.ERROR)

torus1 = Cell.Torus()
torus1 = Topology.Triangulate(torus1)
torus1_shp = Topology.OCCTShape(torus1)

#box1 = BRepPrimAPI_MakeBox(10., 20., 30.).Shape()

print(torus1_shp)
#print(Topology.ByOCCTShape(box1))

#display, start_display, add_menu, add_function_to_menu = init_display()
#display.DisplayShape(Topology.OCCTShape(torus1), update=True)
#start_display()
```

**Comment by wassimj** [comment]
I am not sure what DisplayShape is expecting as input, but this method was meant to make topologic compatible with FreeCAD. It outputs a TopoDS_Shape as you pointed out. Please search your API for a method that converts that or if you can convert a BREP use Topology.String(torus1)

**Comment by tnakaicode** [comment]
DisplayShape requires the type of TopoDS_Shape(TopoDS_Shell, TopoDS_Face, ...) defined in OpenCASCADE to the Input.
It is very close, and I am guessing that without the "topologic." part of topologic.TopoDS_Shape, the types would match and pythonocc-core would be able to draw it.

I have confirmed that I can see it if I output it to brep file. Since the programs are written in the same Python, I am looking for a way to pass the data without going through an external file.

**Comment by wassimj** [comment]
Please try the following. This is not tested and I am not familiar with pythonOCC, but something like below should work in principle. Some syntax may need to be fixed or additional commands need to be included to make it work.

```
# Import the needed libraries
from topologicpy.Cell import Cell
from topologicpy.Topology import Topology
import io
from OCC.BRep import BRep_Builder
import OCC.BRepTools

# Create a Topologic Torus
torus = Cell.Torus()

# Convert the topology to a BRep string
ts = Topology.String(torus, version=1)

# Create an IO stream from the BRep string
iss = io.StringIO(ts)

# Get a BRep_Builder object
bb = BRep_Builder()

# Read the BRep String from the io stream:
occtShape = OCC.BRepTools.Read(occtShape, iss, bb)
```

**Comment by tnakaicode** [comment]
Passing data as a string instead of through File IO is a good idea. I will leave the modified code.

There is one problem: when I put Torus (torus2 in the code) created in pythonocc into Plotly.DataByTopology, the whole Python process stops. even if I start it in Debug mode, the Debugger itself stops. Try running it with the commented out part active.

```python
import sys
import os

sys.path.append(os.path.join("./"))
import topologicpy
# import topologic

from topologicpy.Cell import Cell
from topologicpy.Topology import Topology

from OCC.Display.SimpleGui import init_display
from OCC.Core.gp import gp_Ax2, gp_Pnt, gp_Dir
from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox, BRepPrimAPI_MakeTorus
from OCC.Core.BRepTools import breptools

# torus1: Topologicpy -> OCC
torus1 = Cell.Torus()
torus1 = Topology.Triangulate(torus1)
print(torus1)
torus1_Data = Plotly.DataByTopology(torus1,
                                   faceColor="blue", faceOpacity=0.5, vertexColor=2)

# Convert the topology to a BRep string
torus1_brep = Topology.String(torus1, version=1)

# Read the BRep String from the Brep string
torus1_shpe = breptools.ReadFromString(torus1_brep)
print(torus1_shpe)

# box1: OCC -> Topologicpy
box1 = BRepPrimAPI_MakeBox(1.0, 2.0, 3.).Solid()
box1_brep = breptools.WriteToString(box1)
box1_topo = Topology.ByString(box1_brep)
print(box1_topo)
box1_Data = Plotly.DataByTopology(box1_topo,
                                    faceColor="red", faceOpacity=0.5, vertexColor=2)
    
# torus2: OCC -> Topologicpy
torus2 = BRepPrimAPI_MakeTorus(gp_Ax2(gp_Pnt(0, 0, 1), gp_Dir(0, 0, 1)),
                               0.5, 0.125).Face()
torus2_brep = breptools.WriteToString(torus2)
torus2_topo = Topology.ByString(torus2_brep)
print(torus2_topo)
#torus2_Data = Plotly.DataByTopology(torus2_topo,
#                                    faceColor="red", faceOpacity=0.5, vertexColor=2)

plotlyData = torus1_Data + box1_Data
fig = Plotly.FigureByData(plotlyData, width=950 * 2, height=500 * 2)
Plotly.SetCamera(fig,
                 camera=[1.5, 1.5, 1.5], target=[0, 0, 0], )
Plotly.Show(fig, renderer="browser")

display, start_display, add_menu, add_function_to_menu = init_display()
display.DisplayShape(torus1_shpe, color="BLUE1")
display.DisplayShape(torus2, color="RED")
display.DisplayShape(box1, color="RED")
display.FitAll()
start_display()
```

The viewer in pythonocc is shown figure. The red torus is torus2, and unlike Topologicpy, the surface is drawn as a curved surface.

![image](https://user-images.githubusercontent.com/29787447/226801939-eafe3aa8-ee69-48ec-a28f-104133da0385.png)

**Comment by wassimj** [comment]
Sorry. I cannot debug occ code. Try Topology.Show(torus) without importing and using pythonocc. This might be a bug in pythonocc not in topologicpy which doesn’t use pythonocc

**Comment by wassimj** [comment]
topologicpy by design avoids curved lines and surfaces and cannot display them. Under the hood it can handle them, but many methods assume flat faces and straight edges

**Comment by wassimj** [comment]
In topologicpy, circle, ellipse, cylinder, cone, sphere, and torus are all custom methods that produce shapes made with flat surfaces and straight edges.

**Comment by tnakaicode** [comment]
I understood.
