### ISSUE TITLE
Testing in Python3 Console (Fedora 31)  -  CPyCppyy API not found

### ISSUE THREAD

**Issue by paullee0** [wassimj/topologicPy#17]
Followed all the instruction, helps in OSArch, bitbucket on cppyy...

[paullee@f31 ~]$ python3
Python 3.7.9 (default, Aug 19 2020, 17:05:11) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import topologic
/home/paullee/.local/lib/python3.7/site-packages/cppyy/__init__.py:291: UserWarning: CPyCppyy API not found (tried: /usr/local/include/python3.8); set CPPYY_API_PATH envar to the 'CPyCppyy' API directory to fix
  warnings.warn("CPyCppyy API not found (tried: %s); set CPPYY_API_PATH envar to the 'CPyCppyy' API directory to fix" % apipath_extra)
>>> import cppyy
>>>

**Comment by brunopostle** [comment]
@paullee0 you need to figure out where CPyCppyy is installed and set the CPPYY_API_PATH environment variable, something like this, maybe:

    export CPPYY_API_PATH=$HOME/.local/lib/python3.7/site-packages

or, you may need to experiment:

    export CPPYY_API_PATH=$HOME/.local/lib/python3.7/site-packages/CPyCppyy

**Comment by wlav** [comment]
Ideally, the API is found automatically. There are a couple of locations tried, based on known locations used by various installers and their various configurations (there seems to be no standard ...). It'd be good to post the location and the location of `cppyy.py` so that this case (which apparently isn't covered yet) can be added.

**Comment by paullee0** [comment]
Thanks all, will test :D

**Comment by paullee0** [comment]
Thanks all, but not sure what is going on after searching and asking in  ... [bitbucket](https://bitbucket.org/wlav/cppyy/issues/327/pip-install-cppyy-on-fedora31-not-working)

**Comment by wassimj** [comment]
I am closing this issue, but please feel free to re-open if you need more help.
