### ISSUE TITLE
Dockerized TopologicPy can't find Aperture from TopologicCore

### ISSUE THREAD

**Issue by yonghah** [wassimj/topologicPy#19]
I wrote a dockerfile for TopologicPy and the image was built successfully. But import topologic in the container generates the error like below:

```
root@87f2c0234606:~/topologicbim# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import topologic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/topologic-0.4-py3.8.egg/topologic/__init__.py", line 120, in <module>
    Aperture = TopologicCore.Aperture
AttributeError: <namespace cppyy.gbl.TopologicCore at 0x463ac40> has no attribute 'Aperture'. Full details:
  type object 'TopologicCore' has no attribute 'Aperture'
  descriptor '__repr__' of 'cppyy.CPPInstance' object needs an argument
  'Aperture' is not a known C++ template
  'Aperture' is not a known C++ enum
>>> 
```

FYI, libTopologicCore.so is located under /usr/local/lib and CPPYY_API_PATH has header files. 
```
root@87f2c0234606:~/topologicbim# ls /usr/local/lib
libTopologicCore.so  libTopologicCore.so.0  libTopologicCore.so.0.0.0  python3.8
root@87f2c0234606:~/topologicbim# ls $CPPYY_API_PATH
API.h  CommonDefs.h  DispatchPtr.h  PyException.h  PyResult.h  TPyArg.h
```

FYI2, dockerfile is here for the error reproduction:
```
FROM ubuntu:20.04

USER root
WORKDIR /root/topologicbim

SHELL [ "/bin/bash", "-c" ]

RUN apt-get -qq -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        bzip2 \
        unzip \
        cmake \
        make \
        g++ \
        git \
        libgl-dev \
        libglu-dev \
        libpng-dev \
        libxmu-dev \
        libxi-dev \
        libtbb-dev \
        tcl-dev \
        tk-dev \
        zlib1g-dev \
        libharfbuzz-dev \
        libfreetype-dev \
        libfreeimage-dev \
        libocct-*-dev \
        software-properties-common && \
    apt-get -y autoclean && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*

# install Topologic
RUN git clone https://github.com/NonManifoldTopology/Topologic.git && \
    cd Topologic && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install

# install cppyy via pip
RUN apt-get -qq -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        python3-pip && \
    pip3 install cppyy && \
    ldconfig /usr/local/lib

# Install TopologicPy
RUN git clone http://github.com/wassimj/TopologicPy && \
    cd TopologicPy/cpython && \
    python3 setup.py build && \
    python3 setup.py install

ENV CPPYY_API_PATH /usr/local/include/python3.8/CPyCppyy

CMD [ "/bin/bash" ]
```

Any ideas?

**Comment by wassimj** [comment]
Hi,

 

Yes, I think we messed something up. I am seeing this on Windows as well. Please tell me if these folders exist and what is their contents if they do:

 

/usr/local/include/TopologicCore

 

/usr/include/TopologicCore

 

/usr/local/lib

 

 

From: Yongha Hwang ***@***.***> 
Sent: 30 March 2021 06:45
To: wassimj/topologicPy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wassimj/topologicPy] Dockerized TopologicPy can't find Aperture from TopologicCore (#19)

 

I wrote a dockerfile for TopologicPy and the image was built successfully. But import topologic in the container generates the error like below:

***@***.***:~/topologicbim# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import topologic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/topologic-0.4-py3.8.egg/topologic/__init__.py", line 120, in <module>
    Aperture = TopologicCore.Aperture
AttributeError: <namespace cppyy.gbl.TopologicCore at 0x463ac40> has no attribute 'Aperture'. Full details:
  type object 'TopologicCore' has no attribute 'Aperture'
  descriptor '__repr__' of 'cppyy.CPPInstance' object needs an argument
  'Aperture' is not a known C++ template
  'Aperture' is not a known C++ enum
>>> 

FYI, libTopologicCore.so is located under /usr/local/lib and CPPYY_API_PATH has header files.

***@***.***:~/topologicbim# ls /usr/local/lib
libTopologicCore.so  libTopologicCore.so.0  libTopologicCore.so.0.0.0  python3.8
***@***.***:~/topologicbim# ls $CPPYY_API_PATH
API.h  CommonDefs.h  DispatchPtr.h  PyException.h  PyResult.h  TPyArg.h

FYI2, dockerfile is here for the error reproduction:

FROM ubuntu:20.04
 
USER root
WORKDIR /root/topologicbim
 
SHELL [ "/bin/bash", "-c" ]
 
RUN apt-get -qq -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        bzip2 \
        unzip \
        cmake \
        make \
        g++ \
        git \
        libgl-dev \
        libglu-dev \
        libpng-dev \
        libxmu-dev \
        libxi-dev \
        libtbb-dev \
        tcl-dev \
        tk-dev \
        zlib1g-dev \
        libharfbuzz-dev \
        libfreetype-dev \
        libfreeimage-dev \
        libocct-*-dev \
        software-properties-common && \
    apt-get -y autoclean && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*
 
# install Topologic
RUN git clone https://github.com/NonManifoldTopology/Topologic.git && \
    cd Topologic && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install
 
# install cppyy via pip
RUN apt-get -qq -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        python3-pip && \
    pip3 install cppyy && \
    ldconfig /usr/local/lib
 
# Install TopologicPy
RUN git clone http://github.com/wassimj/TopologicPy && \
    cd TopologicPy/cpython && \
    python3 setup.py build && \
    python3 setup.py install
 
ENV CPPYY_API_PATH /usr/local/include/python3.8/CPyCppyy
 
CMD [ "/bin/bash" ]

Any ideas?

**Comment by yonghah** [comment]
Sure. Here's the contents of the three locations. 
/usr/include/TopologicCore doesn't exists.

```
root@68ec05c4fbdb:~/topologicbim# ls /usr/local/include/TopologicCore/
About.h             CellComplexFactory.h  DoubleAttribute.h  InstanceGUIDManager.h  ShellFactory.h            Utilities.h
Aperture.h          CellFactory.h         Edge.h             IntAttribute.h         StringAttribute.h         Vertex.h
ApertureFactory.h   Cluster.h             EdgeFactory.h      Line.h                 Surface.h                 VertexFactory.h
Attribute.h         ClusterFactory.h      Face.h             ListAttribute.h        TopologicalQuery.h        Wire.h
AttributeManager.h  ContentManager.h      FaceFactory.h      NurbsCurve.h           Topology.h                WireFactory.h
Bitwise.h           Context.h             Geometry.h         NurbsSurface.h         TopologyFactory.h
Cell.h              ContextManager.h      GlobalCluster.h    PlanarSurface.h        TopologyFactoryManager.h
CellComplex.h       Dictionary.h          Graph.h            Shell.h                Utilities
root@68ec05c4fbdb:~/topologicbim# ls /usr/include/TopologicCore
ls: cannot access '/usr/include/TopologicCore': No such file or directory
root@68ec05c4fbdb:~/topologicbim# ls /usr/local/lib
libTopologicCore.so  libTopologicCore.so.0  libTopologicCore.so.0.0.0  python3.8
root@68ec05c4fbdb:~/topologicbim# 
```

**Comment by wassimj** [comment]
These locations and their contents are correct:

The culprit is on line 115 of topologicPy/cpython/topologic/__init.py
We need to have been able to load the TopologicCore library and all the headers.
Can you please test the following in python and report back? Thanks
```
import cppyy
cppyy.add_include_path("/usr/local/include/TopologicCore")
cppyy.add_library_path("/usr/local/lib")
cppyy.load_library("TopologicCore")
cppyy.include("/usr/local/include/TopologicCore/Aperture.h" )
from cppyy.gbl import TopologicCore
Aperture = TopologicCore.Aperture


```

**Comment by wlav** [comment]
(Just now waking up in my time zone. :) ) Yes, I believe you already found it.

Just for the record, though: 1) standard include paths such as `/usr/include` and `/usr/local/include` need not be added on Linux; and 2) after adding any paths, custom or otherwise, `include()`s should be relative and not use absolute paths.

If either 1) or 2) isn't true, that'd be a bug in Cling. :)

Aside, my personal preference would have been to find `TopologicCore` relative to `TopologicPy`, rather than in some absolute location, or to save the location as found on installation time (e.g. through the use of `cmake`'s package find or as part of a `config.py`). Or, even better, use dictionaries (https://cppyy.readthedocs.io/en/latest/utilities.html#dictionaries) on install, as these store the build-time include paths internally.

**Comment by yonghah** [comment]
Here's the result.
cppyy.include("/usr/local/include/TopologicCore/Aperture.h" ) fails. 

```
root@69edf347b548:~/topologicbim# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
>>> cppyy.add_include_path("/usr/local/include/TopologicCore")
>>> cppyy.add_library_path("/usr/local/lib")
>>> cppyy.load_library("TopologicCore")
True
>>> cppyy.include("/usr/local/include/TopologicCore/Aperture.h")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cppyy/__init__.py", line 229, in include
    raise ImportError('Failed to load header file "%s"%s' % (header, err.err))
ImportError: Failed to load header file "/usr/local/include/TopologicCore/Aperture.h"
In file included from input_line_21:1:
In file included from /usr/local/include/TopologicCore/Aperture.h:19:
/usr/local/include/TopologicCore/Utilities.h:19:10: fatal error: 'TopoDS_Shape.hxx' file not found
#include <TopoDS_Shape.hxx>
         ^~~~~~~~~~~~~~~~~~

>>> from cppyy.gbl import TopologicCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TopologicCore' from '' (unknown location)
>>> Aperture = TopologicCore.Aperture
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'TopologicCore' is not defined
>>> 
```

**Comment by wlav** [comment]
`TopoDS_Shape.hxx` is part of OpenCascade. Presumably `apt-get` of `libocct-*-dev` should have pulled it in. Can you verify whether it can be found under `/usr/include/opencascade` or `/usr/local/include/opencascade`? And add the relevant include paths before `include()`-ing `Aperture.h`? (`TopologicPy` does this automatically, btw.)

**Comment by yonghah** [comment]
@wlav Yes. OpenCascade is installed under /usr/include/opencascade. 
cppyy.add_include_path("/usr/include/opencascade") resolves the issue with Aperture.h.


```
root@a6ddfbe89568:~/topologicbim# python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
>>> cppyy.add_include_path("/usr/local/include/TopologicCore")
>>> cppyy.add_include_path("/usr/include/opencascade")
>>> cppyy.add_library_path("/usr/local/lib")
>>> cppyy.load_library("TopologicCore")
True
>>> cppyy.include("/usr/local/include/TopologicCore/Aperture.h" )
True
>>> from cppyy.gbl import TopologicCore
>>> Aperture = TopologicCore.Aperture
>>> 
```

**Comment by wassimj** [comment]
@wlav Something strange is still going on. I tested loading the __init__.py file into python line-by-line and in that test, Aperture loaded correctly, but then the next line (ApertureFactory) failed.

`>>> import cppyy
>>> import os
>>> import platform
>>> import sys
>>> 
>>> headers = [
... "About.h",
... "Aperture.h",
... "ApertureFactory.h",
... "Attribute.h",
... "AttributeManager.h",
... "Bitwise.h",
... "Cell.h",
... "CellComplex.h",
... "CellComplexFactory.h",
... "CellFactory.h",
... "Cluster.h",
... "ClusterFactory.h",
... "ContentManager.h",
... "Context.h",
... "ContextManager.h",
... "Dictionary.h",
... "DoubleAttribute.h",
... "Edge.h",
... "EdgeFactory.h",
... "Face.h",
... "FaceFactory.h",
... "Geometry.h",
... "GlobalCluster.h",
... "Graph.h",
... "InstanceGUIDManager.h",
... "IntAttribute.h",
... "Line.h",
... "ListAttribute.h",
... "NurbsCurve.h",
... "NurbsSurface.h",
... "PlanarSurface.h",
... "Shell.h",
... "ShellFactory.h",
... "StringAttribute.h",
... "Surface.h",
... "TopologicalQuery.h",
... "Topology.h",
... "TopologyFactory.h",
... "TopologyFactoryManager.h",
... "Utilities.h",
... "Utilities.h",
... "Utilities/CellUtility.h",
... "Utilities/Direction.h",
... "Utilities/EdgeUtility.h",
... "Utilities/FaceUtility.h",
... "Utilities/ShellUtility.h",
... "Utilities/TopologyUtility.h",
... "Utilities/TransformationMatrix2D.h",
... "Utilities/Vector.h",
... "Utilities/VertexUtility.h",
... "Utilities/WireUtility.h",
... "Vertex.h",
... "VertexFactory.h",
... "Wire.h",
... "WireFactory.h"
... ]
>>> 
>>> def pythonize_topologic_printing(klass, name):
...     if 'GetTypeAsString' in klass.__dict__:
...         klass.__str__ = klass.__repr__ = lambda self: str("<Topologic "+self.GetTypeAsString()+">")
...     elif "Dictionary" in klass.__repr__():
...         klass.__str__ = klass.__repr__ = lambda self: str("<Topologic Dictionary>")
... 
>>> cppyy.py.add_pythonization(pythonize_topologic_printing, 'TopologicCore')
>>> 
>>> system = platform.system()
>>> if system != 'Windows':
...     if (os.path.isdir("/usr/local/include/opencascade")):
...         cppyy.add_include_path("/usr/local/include/opencascade")
...     elif (os.path.isdir("/usr/include/opencascade")):
...         cppyy.add_include_path("/usr/include/opencascade")
...     if (os.path.isdir("/usr/local/include/TopologicCore")):
...         topologic_inc = "/usr/local/include/TopologicCore"
...     elif (os.path.isdir("/usr/include/TopologicCore")):
...         topologic_inc = "/usr/include/TopologicCore"
...     if (os.path.isdir("/usr/local/lib")):
...         cppyy.add_library_path("/usr/local/lib")
... else:
...     win_prefix = "E:/Documents/Projects/TopologicFinal/topologic"
...     topologic_inc = "{}/TopologicCore/include".format( win_prefix )
...     opencascade_prefix = "C:/OpenCASCADE-7.4.0-vc14-64"
...     cppyy.add_include_path("{}/opencascade-7.4.0/inc".format(opencascade_prefix))
...     cppyy.add_library_path("{}/output/x64/Release".format(win_prefix))
...     cppyy.add_library_path("{}/opencascade-7.4.0/win64/vc14/bin".format(opencascade_prefix))
... 
>>> cppyy.add_include_path(topologic_inc)
>>> 
>>> cppyy.load_library("TopologicCore")
True

>>> 
>>> for header in headers:
...     cppyy.include(topologic_inc + "/" + header )
... 
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

>>> from cppyy.gbl import TopologicCore
>>> from cppyy.gbl import TopologicUtilities
>>> 
>>> Aperture = TopologicCore.Aperture
>>> ApertureFactory = TopologicCore.ApertureFactory
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: <namespace cppyy.gbl.TopologicCore at 0x562e705f1c80> has no attribute 'ApertureFactory'. Full details:
  type object 'TopologicCore' has no attribute 'ApertureFactory'
  descriptor '__repr__' of 'cppyy.CPPInstance' object needs an argument
  'ApertureFactory' is not a known C++ template
  'ApertureFactory' is not a known C++ enum
`

**Comment by wlav** [comment]
Problem is this line in your pythonizor:
```
 elif "Dictionary" in klass.__repr__():
```
A call to `__repr__` requires an instance, but it is given only the class, so missing an argument, hence this error:
```
descriptor '__repr___' of 'cppyy.CPPInstance' object needs an argument
```
during pythonization (i.e. after the class has been properly found by cppyy).

**Comment by wassimj** [comment]
Thank you @wlav. It seem that has resolved the issue but now I am wondering how to pythonize the class representation of classes in Topologic (e.g. Dictionary) that do not have a GetTypeAsString method.

**Comment by wlav** [comment]
If they don't have a `GetTypeAsString`, but there is some other general method, just check for that. If the different `__str__` is for _all_ classes that don't have such a method, just fill out the `else` block. (The pythonizor is registered on the `TopologicCore` namespace, so it will only ever be called for classes that are bound from this namespace.) If the purpose is only to check for the name to locate specific classes, check the `name` variable (second argument to the pythonizor), or check `klass.__cppname__`.

**Comment by wassimj** [comment]
Thank you. I simplified the method to just use the name argument. Tested it and it works fine. I updated the repo.

```
def pythonize_topologic_printing(klass, name):
    klass.__str__ = klass.__repr__ = lambda self: str("<Topologic "+name+">")

cppyy.py.add_pythonization(pythonize_topologic_printing, 'TopologicCore')
```
