### ISSUE TITLE
topologicpy 0.0.22: Topology.ExportToBRep(v=1) not writing results suitable for Topology.ByImportedBRep

### ISSUE THREAD

**Issue by jpstaub** [wassimj/topologicpy#2]
Configuration:
Windows 10
Revit 2021.1.3 / Dynamo Core 2.6.1.8786 / Dynamo Revit 2.6.1.8850 / Topologic 1.4.0
Blender 3.4.1 / Sverchok 1.2.0 / TopologicSverchok 2023-01-05 v0.8.3.0
python 3.8.15 / topologicpy 0.0.22 / pip 22.3.1

After coplanar faces are removed from faces it appears that topologicpy0.0.22.Topology.ExportTBRep(v=1) does not export desired results to the BRep file.

Figure 5 and 6 of the attached pdf show the results of Topology.ExportToBRep(v=1) and Topology.ExportToBRep(v=3) in Blender. v=1 exported results with coplanar faces after coplanar faces were removed. v=3 exported results without coplanar faces after coplanar faces were removed.

[Ripcord_Revit21 Topology.RemoveCoplanarFaces_23-01-17.pdf](https://github.com/wassimj/topologicpy/files/10436486/Ripcord_Revit21.Topology.RemoveCoplanarFaces_23-01-17.pdf)

Subsequent debugging revealed Topology.ExportToBRep_v1 produces a result that Topology.ByImportedBRep unwraps to Cells with CoplanarFaces where Cells intersect with one another. The reason CoplanarFaces on exterior faces are not observed is that exterior faces by definition do not intersect the faces of adjacent Cells. This was observed in Blender and Dynamo Revit. The root problem is more likely than not Topology.SelfMerge used as a workaround in Topology.ExportToBRep_v1. 

Please see attached for an updated pdf that expands on the observation above.

[Ripcord_Revit21 Topology.RemoveCoplanarFaces_23-01-20.pdf](https://github.com/wassimj/topologicpy/files/10470035/Ripcord_Revit21.Topology.RemoveCoplanarFaces_23-01-20.pdf)

Request: please revise Topology.ExportToBRep(v=1) so that results of topologicpy operations are reflected by Topology.ByImportedBRep when working with Clusters.

**Tested workaround: Cells processed individually.**

An enumerator for BRep format Version which first appears in the OpenCascade 7.6 documentation. Please [click here](https://dev.opencascade.org/doc/occt-7.6.0/refman/html/_top_tools___format_version_8hxx.html#a067cf02a33b3fdbbf3e4d2be6efb5f0c) for details. This gives insight on differences between BRep Versions 1-3.

OpenCascade 7.4 used by [Topologic v1.4.0 ](https://topologic.app/bin/Topologic-1.4.0-ReleaseNotes.pdf)does not include a BRep Version option for Write(). Please [click here](https://dev.opencascade.org/doc/occt-7.4.0/refman/html/class_b_rep_tools.html#a17bd53a44b6a0e2b3de7726d8a575005) for details.

If topologicpy incorporated the ability to explicitly set BRep Version for OpenCascade 7.6+ BRep compatibility with Topologic v1.4.0 should be restored. Please consider incorporating the ability to explicitly set BRep Version into topologicpy.

**Comment by wassimj** [comment]
Since this was done in Blender, I suspect you are using TopologicSverchok not topologicpy. Can you test in a jupyter notebook using topologicpy and report back? If indeed this is a bug with TopologicSverchok, please report this bug on that software’s bug tracker/issues page.

**Comment by wassimj** [comment]
Correct brep versioning is now from 0.2.X. When exporting you can now specify version=1 or 2 or 3.
