### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by jgunstone** [wassimj/topologicpy#24]
hi there, 

really excited to try this out! 
just did the following and am running into errors....

```console
mamba create -n topologicpy-dev pip
pip install topologicpy --upgrade
cd ~
git clone git@github.com:wassimj/topologicpy.git
mamba install jupyterlab
cd topologicpy
jupyter lab
```
**note**. running on Ubuntu2004

launching a jupyter lab session in this repo with the topologicpy environment. 
then running a notebook; 
![image](https://github.com/wassimj/topologicpy/assets/21370980/c70aaf5f-5820-4523-8aa5-f94b3db523d7)

the same happens in other notebooks

do you know what the issue is? 

many thanks

**Comment by wassimj** [comment]
I am not 100% sure, but I am suspecting that you did the following:
1. pip installed topologicpy
2. But then you cloned the directory from github which does not include the binaries.
So when you are within topologicpy folder and trying to run topologicpy. It is looking for the topologic (Core) binaries inside the bin/linux/topologic folder and it is not finding it.
You should just simply pip install topologicpy and use it as is. Do not clone the github directory. And work from a different folder that you set up for your project/experiments. Do not run from inside the topologicpy folder where it is installed.

**Comment by jgunstone** [comment]
thanks for the quick response - 

![image](https://github.com/wassimj/topologicpy/assets/21370980/311fb9e0-a841-4482-8724-b4dd418d6cbc)

^ running from a simple python console launched in a different folder appears to produce the same error 

to be sure - i just went through the same process from scratch with no interaction with Github
```
mamba create -n topo-dev python pip
pip install topologicpy
```
![image](https://github.com/wassimj/topologicpy/assets/21370980/b1b27aa3-9351-49f3-98cd-f79492c8cbab)


tracing the error - 
it looks like the bin folder was installed correctly:
![image](https://github.com/wassimj/topologicpy/assets/21370980/892cc1cd-d30f-4b52-8b65-1d29ef1e0d36)


the `import topologic` command in the `__init__.py` file appears to be causing the problem. so I added a print command on the path that is `sys.path.append(...)`ed in the hope that that is useful information.... 

<img width="809" alt="image" src="https://github.com/wassimj/topologicpy/assets/21370980/31accb13-d9b8-4cbd-92f3-dacb6393885b">


based on the folder structure it looks like it should be sys appending the `topologic` folder rather than the `topologic.libs` folder so i edited the `__init__.py` file as follows: 

<img width="984" alt="image" src="https://github.com/wassimj/topologicpy/assets/21370980/179745d6-83ca-4880-8b8e-e4383f94c0bf">


which appears to have fixed the problem... 

so it looks as thought there is a minor error in the `__init__.py` file ? 

--- 

installed from windows works without problem. 

many thanks

**Comment by wassimj** [comment]
Amazing investigation! Then it had nothing to do with git cloning. Yes it seems there is a bug in the init file. I made a silly change at one point that caused this. I should not have called both folders starting with topologic (topologic and topologic.libs)! I will fix and issue a new release soon.

**Comment by wassimj** [comment]
Hi @jgunstone Can you please install version 0.4.26 from scratch and test and let me know if it now works? Thank you again!

**Comment by jgunstone** [comment]
looks good! 

![image](https://github.com/wassimj/topologicpy/assets/21370980/9c4a3196-4d3f-4556-ba78-a4ef42de6577)

thanks very much for the quick fix

**Comment by wassimj** [comment]
Excellent! Closing this issue.
