### ISSUE TITLE
Wire.BoundingRectangle

### ISSUE THREAD

**Issue by gaoxipeng** [wassimj/topologicpy#26]
On line 57 of Wire.BoundingRectangle:

xTran = None
        # Create a sample face
        while not xTran:
            vertices = Topology.SubTopologies(topology=topology, subTopologyType="vertex")
            v = sample(vertices, 3)
            w = Wire.ByVertices(v)
            f = Face.ByWire(w)
            f = Face.Flatten(f)
            dictionary = Topology.Dictionary(f)
            xTran = Dictionary.ValueAtKey(dictionary,"xTran")

Sometimes, it may happen that three points lie on the same line, and f = Face.ByWire(w) returns None. Then, dictionary = Topology.Dictionary(f) prints "Topology.Dictionary - Error: the input topology is not a valid topology. Returning None." I suggest modifying it as follows to avoid this error:

    f = None
    # Create a sample face
    while not f:
        vertices = Topology.SubTopologies(topology=topology, subTopologyType="vertex")
        v = sample(vertices, 3)
        w = Wire.ByVertices(v)
        f = Face.ByWire(w)
    f = Face.Flatten(f)
    dictionary = Topology.Dictionary(f)
    xTran = Dictionary.ValueAtKey(dictionary, "xTran")

**Comment by wassimj** [comment]
Thank you for spotting this bug. I have modified the code as follows:
1. I added a method called Vertex.AreCollinear(vertices) to check if the three vertices are collinear:
2. Then I modified the main code as follows:
```
        vertices = Topology.SubTopologies(topology=topology, subTopologyType="vertex")
        start = time.time()
        period = 0
        result = True
        while result and period < 30:
            vList = sample(vertices, 3)
            result = Vertex.AreCollinear(vList)
            end = time.time()
            period = end - start
        if result == True:
            print("Wire.BoundingRectangle - Error: Could not find three vertices that are not colinear within 30 seconds. Returning None.")
            return None
```
The code has been updated on GitHub and will be included with the next release of topologicpy on pip.
If you can test and report back that would be great! Thank you!

**Comment by wassimj** [comment]
I'm closing this as I believe it is solved, but if you are still facing issues, please feel free to re-open.
