### ISSUE TITLE
Plotly.DataByTopology

### ISSUE THREAD

**Issue by gaoxipeng** [wassimj/topologicpy#27]
from topologicpy.Wire import Wire
from topologicpy.Topology import Topology
from topologicpy.Plotly import Plotly
import plotly.offline as ofl

star = Wire.Star()
star = Topology.Rotate(star, degree=33)
br = Wire.BoundingRectangle(star, optimize=10)
plotly_data = Plotly.DataByTopology(br)
plotly_figure = Plotly.FigureByData(plotly_data)
print(plotly_data)
ofl.plot(plotly_figure)

The above code may have a chance of not visualizing correctly, displaying a blank page.The z-coordinates of rectangle contain very small numbers likes 1.22464679914824e-13, which cannot be correctly displayed using plotly.
I try modify the Plotly.py

line 531, 563, 671:

x.append(v[0])
y.append(v[1])
z.append(v[2])

 to:

                    x.append(round(v[0],5))
                    y.append(round(v[1],5))
                    z.append(round(v[2],5))

and

line 610, 644:

x+=[sv[0],ev[0], None] # x-coordinates of edge ends
y+=[sv[1],ev[1], None] # y-coordinates of edge ends
z+=[sv[2],ev[2], None] # z-coordinates of edge ends

to:

                    x+=[round(sv[0],5),round(ev[0],5), None] # x-coordinates of edge ends
                    y+=[round(sv[1],5),round(ev[1],5), None] # y-coordinates of edge ends
                    z+=[round(sv[2],5),round(ev[2],5), None] # z-coordinates of edge ends

Then it can be displayed correctly.
I think use round() abandoning too small a part can solve this problem.

**Comment by wassimj** [comment]
Thank you for reporting this issue. Although I couldn't replicate it on my machine, there is no harm in adding a round(x,y) on vertex coordinates for display as they usually have far more digits after the decimal point than needed. Therefore, I added an optional 'mantissa' int argument to the Plotly methods where needed. The usual default is 4 not 5, but I think that would work just as well. This has been pushed to github and will be included in the next release. If you can test the version I have on github and confirm that it works for you, that would be great. Another thing is that I noticed you do not use Plotly.Show(plotly_figure). Why is that?

**Comment by gaoxipeng** [comment]
The latest Plotly.py is able to display correctly. Thank you very much for your efforts.
I use PyCharm as my IDE, so I use ofl.plot(plotly_figure) or Plotly.Show(plotly_figure, renderer='browser').  When I first started using topologicpy, I didn't know about adding renderer='browser'. This works fine in Jupyter Notebook, but it doesn't open in the browser. On your previous Twitter , there was ofl.iplot(plotly_figure), which can open and display in the browser. So, sometimes I use ofl.iplot(plotly_figure).

**Comment by wassimj** [comment]
On my machine, using Plotly.Show(plotly_figure, renderer="browser") does open the figure in a new web browser window. For a list of renderers, you can use Plotly.Renderers(). In any case, I added "offline" as an optional renderer. If you specify that in Topology.Show(topology, renderer="offline"), it should work for PyCharm. Please test latest version on github. Thanks
