### ISSUE TITLE
pyvisTutorial error

### ISSUE THREAD

**Issue by anydel1** [wassimj/topologicpy#28]
Hello, 
A small thing. I've been working though the pyvis tutorial step by step to build up my skills and came across an error in the assignDictionary function.
It appears to all work fine. Plotly renders the graph, and the queries seem to return everything fine. But this has been nagging at me.
Is there something I'm missing when calling  "print type" on (t) ?
![pyvisError](https://github.com/wassimj/topologicpy/assets/77734628/59a5df1f-1ba4-418e-a4a7-9dec06825465)

**Comment by wassimj** [comment]
t is defined within the function and you are trying to print it outside that function so it out of scope. This is user error 😉

**Comment by anydel1** [comment]
> t is defined within the function and you are trying to print it outside that function so it out of scope. This is user error 😉

Thank you Wassim! I'm learning, sometimes slowly.
