### ISSUE TITLE
Topology.String_GraphByTopology

### ISSUE THREAD

**Issue by anydel1** [wassimj/topologicpy#29]
Parameter storeBRep in Graph.ByTopology not working.

Wassim hello,
I'm working on part two of my Topologicpy - Neo4j workflow. I have two files. One for sending to Neo4j, and another for recieving from Neo4j. I've been following the logic of your blender tutorial to build the script and ran into an error when setting storeBRep=True. I got a warning that Topology.String was depricated use Topology.BREPString. I updated Topologicpy and saw the method was completely removed, but the parameter storeBRep was still present in GraphByTopology.  I used Topology.BREPString to retrieve the string, added was able to add it to the dictionary as in the attached image. The brepstring is sent to Neo4j and I can see it as a property in each cell. However I am stuck in the second file that retrieves the Neo4j graph. I'm able to access the BRepString, but Topology.ByBREPString returns "none" I'm uncertain where I went wrong. Perhaps my inexperience.
The files can be found at my GitHub: https://github.com/anydel1/Topologicpy_Neo4j.git
![Topology StringError](https://github.com/wassimj/topologicpy/assets/77734628/31195ab7-d50a-40fb-adbe-53a107d967ec)
![Neo4jProps](https://github.com/wassimj/topologicpy/assets/77734628/433384b2-ff83-405b-9768-d182db17eaf8)
![neoToTpy](https://github.com/wassimj/topologicpy/assets/77734628/01337bda-c2ad-4577-8952-8fcb088a276e)

**Comment by wassimj** [comment]
Can you please send me the brep string that is causing Topology.ByBREPString to return None? Thanks

**Comment by anydel1** [comment]
Hello! I upgraded to the latest version and tried again. After some perseverance I was able to get it to work this time! Two different ways. One by adding the BREPString to the dictionary, and the other using the storeBRep parameter. I was struggling with nested dictionaries. The problem was my code not Topologicpy, but when I created the issue I wasn't sure. I'll close it now. Related to this. What is the most appropriate forum to get help if really struggling with Topologic related concepts, coding, or workflows, etc.? I generally try to work things out on my own, but sometimes could use some feedback. I'm sure you need to  limit such things, but is it best to ask here?, or OSarch? email? 

Best, 
Anthony

**Comment by wassimj** [comment]
Glad you solved it. OSArch is probably the best place to get help from the community and myself: [OSArch Topologic Forum](https://community.osarch.org/discussion/131/topologic-redefining-bim-through-spatial-topology-information-and-grammars)
