### ISSUE TITLE
ModuleNotFoundError: No module named 'topologic' when trying to import topologicpy

### ISSUE THREAD

**Issue by suiramnalim** [wassimj/topologicpy#30]
Hello  

This package looks amazing an I could install topologicpy using pip. However, when I try to import topologicpy I get the follwoing error: ModuleNotFoundError: No module named 'topologic'. I am using anaconda, with the spyder IDE with python 3.11 on a M2 Mac. Is there something super simple I am missing or is there really something that is not working? 

<img width="609" alt="Bildschirmfoto 2023-09-21 um 11 00 02" src="https://github.com/wassimj/topologicpy/assets/122936541/0766f817-9efc-48d0-9bab-e719de58954e">

**Comment by wassimj** [comment]
Hi @suiramnalim,
Sorry to disappoint you, but we do not support MacOS at this time. If you know what you are doing, you can probably build it from source. I'm hoping to build it for MacOS Apple Silicon in the next 1 or 2 months.

**Comment by suiramnalim** [comment]
Hey @wassimj 
Thanks a lot for your fast answer. If its taking 1 to 2 months I gladly wait instead of getting lost in building it from source. Looking forward to try it out.

**Comment by wassimj** [comment]
Hi @suiramnalim,
I have built it for Apple Silicon! Can you please try again with **pip install topologicpy --upgrade**  ? Thanks for testing it.

**Comment by suiramnalim** [comment]
Hi @wassimj 
That was fast. Thanks a lot. I installed it in a fresh conda environment (python 3.11) and it seems to work.
