### ISSUE TITLE
Topology.ReplaceVertices

### ISSUE THREAD

**Issue by gaoxipeng** [wassimj/topologicpy#31]
from topologicpy.Vertex import Vertex
from topologicpy.Edge import Edge
from topologicpy.Wire import Wire
from topologicpy.Topology import Topology

v1 = Vertex.ByCoordinates(0, 0, 0)
v2 = Vertex.ByCoordinates(500, 500, 0)
v3 = Vertex.ByCoordinates(1000, 0, 0)

v4 = Vertex.ByCoordinates(1000, 500, 0)

e1 = Edge.ByStartVertexEndVertex(v1, v2)
e2 = Edge.ByStartVertexEndVertex(v2, v3)

w1 = Wire.ByEdges([e1, e2])
print(Topology.Geometry(w1))

w2 = Topology.ReplaceVertices(w1, [v2], [v4])

Topology.Show(w2, renderer='browser')

The above code is in 0.4.41, returning None
In Topology.py，remove line 4698，4701，

and line 1199：
returnTopology = topologyByEdges(topEdges,outputMode='default')

then add         faces = [] in line 1169
the code can run

But the above modifications can only make this code run,

I think Topology.Geometry(w1) should be
{'vertices': [[0.0, 0.0, 0.0], [500.0, 500.0, 0.0], [1000.0, 0.0, 0.0]], 'edges': [[0, 1], [1, 2]], 'faces': []}
rather than 
{'vertices': [[0.0, 0.0, 0.0], [500.0, 500.0, 0.0], [1000.0, 0.0, 0.0]], 'edges': [[0, 1], [1, 2]], 'faces': [[]]}
If w1 does not include face

**Comment by wassimj** [comment]
(updated response). What a coincidence! I was just fixing this bug today. The reason faces is [[]] and not [] is because this is what Blender expects. I have fixed this and this will be included in the next release, but the files on github have already been updated.

**Comment by wassimj** [comment]
Dear @gaoxipeng
I just release topologicpy 0.4.42 Can you please test and let me know if this bug is now resolved? Thanks!

**Comment by gaoxipeng** [comment]
Thank you very much. This problem has been resolved
