### ISSUE TITLE
CellComplex.ByCells not working as expected

### ISSUE THREAD

**Issue by agonzalezesteve** [wassimj/topologicpy#32]
With a simple test file of a building with 6 Cells: CellComplex.ByCells creates a Cluster with 6 Cells and topologic.CellComplex.ByCells creates a CellComplex with 7 Cells.

![image](https://github.com/wassimj/topologicpy/assets/38532229/c66a0f21-61d0-42a0-a4f1-b7a090ebf42d)

CellComplex.ByCells should create a CellComplex with 6 Cells. Why CellComplex.ByCells creates a Cluster?

The unexpected Cell is a flat Cell with no volume that corresponds to an interior Face of the CellComplex. Why is this new Cell with no volume appearing?

[test_simple_space.zip](https://github.com/wassimj/topologicpy/files/12726728/test_simple_space.zip)

**Comment by wassimj** [comment]
Hi @agonzalezesteve,
I'm trying to load your JSON file, but every time I try it, it kills the kernel. Can you send me the 6 cells using breps? and a python script to load them?

**Comment by agonzalezesteve** [comment]
Here you have.

[import_brep.zip](https://github.com/wassimj/topologicpy/files/12736694/import_brep.zip)

**Comment by wassimj** [comment]
Both topologicpy and topologic behave exactly the same, returning 7 cells of exactly the same volume and in the same order. I believe this is an issue with how the model is created originally with tolerance where two faces that are supposed to be coplanar are ever so slightly off and creating a a very thin 7th cell.
<img width="761" alt="Adria-Test" src="https://github.com/wassimj/topologicpy/assets/6302909/99bf1b9a-0545-478b-b9b9-f8ed221ebe11">

**Comment by wassimj** [comment]
Upon further investigating, I found the culprits. It is only Cell 2 and Cell 3 in the original model that when merged form a CellComplex with 3 Cells. That means that two faces at the corner are not perfectly aligned it seems.
<img width="758" alt="corner" src="https://github.com/wassimj/topologicpy/assets/6302909/edf6ba01-062a-4c96-9a24-d7cbed02b836">

**Comment by wassimj** [comment]
So the coordinates in the vertices are not clean and are off by a small tolerance. Once I forced the numbers to a certain tolerance (a mantissa of 1), it worked fine.
<img width="222" alt="numbers" src="https://github.com/wassimj/topologicpy/assets/6302909/7dd08522-14e0-4d13-b303-f3f494c0c8dc">
<img width="922" alt="Laundry" src="https://github.com/wassimj/topologicpy/assets/6302909/5d14f194-667a-45dd-9067-e0851ac5b96e">

**Comment by agonzalezesteve** [comment]
Cool, solved! Thanks.

**Comment by wassimj** [comment]
Glad it was solved.
