### ISSUE TITLE
Topology.Show()

### ISSUE THREAD

**Issue by gaoxipeng** [wassimj/topologicpy#40]
I tried using Topology Show(), when showVertices=False is added, all faces will be displayed in purple：
```python
from topologicpy.Topology import Topology
from topologicpy.Wire import Wire
from topologicpy.Face import Face

w = Wire.Star(rays=8)
f = Face.ByWire(w)

Topology.Show(f, renderer='offline', faceColor='blue', showVertices=False)
``` 
![image](https://github.com/wassimj/topologicpy/assets/86838581/02a3bd84-115c-4c83-926e-49e6f76016ec)

My processor is Intel 12700H, and for my test data, I use Topology Show() takes half an hour or even more to load a model with a data volume like the one below. The current data can only be loaded in memory, but saving them as brep or obj cannot further use topologicpy functions for subsequent processing, and semantic information will be lost.
![image](https://github.com/wassimj/topologicpy/assets/86838581/0e7f063e-590f-434a-8c6f-441f38fea597)

I attempted to use VTK for visualization, but due to the incorrect order of points, the following results were generated. I am not sure that this library has higher efficiency compared to plotly. I may need to create a GUI based on topologicpy to support some interaction in the future. Does topologicpy support interaction with the database and store topologicpy data in databases such as PostgreSQL and MySQL for subsequent queries and visualization?
![image](https://github.com/wassimj/topologicpy/assets/86838581/55b32110-f4d6-4a78-8935-525bc808efbe)

**Comment by wassimj** [comment]
Dear @gaoxipeng,
Let me address your issue(s) point by point:
1. The issue of the purple colour is a bug. I have fixed it internally and it will be included in the next release.
2. The issue of long rendering time: That amount of volume should not take half an hour. This was a bug in a previous release, so I am wondering if you have updated topologicpy or not. Always include the version number of topologicpy so I can understand if this is a current or old bug that has already been fixed.
3. Saving as brep or obj loses semantic information: You should use Topology.ExportToJSON and Topology.ByJSONPath as not to lose any semantic information.
4. VTK: Sorry, we do not support VTK and it seems the order of points is a result of not translating your mesh data correctly so it is compatible with VTK. If the "star" displays correctly in Plotly, that means the data is correct (for Plotly). VTK may need the data to be modified.
5. topologicpy can store data with Speckle and with NEO4j. There is nothing preventing it from storing data in other databases, but a plugin/script must be written by someone.
I hope the above is helpful. Please let me know if rendering time is improved if you upgrade to the latest or if it is still slow even with the latest version. If so, please send me the brep file(s) for me to test.

**Comment by wassimj** [comment]
<img width="1007" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/e84f8119-0b4d-400c-b2d6-d24ac2c79b08">

**Comment by wassimj** [comment]
<img width="869" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/de5ead94-51cf-441f-83ac-c90c3c1986d2">

**Comment by gaoxipeng** [comment]
Thank you very much for your patient replies and guidance; they have been truly helpful to me.

I test use json in 0.4.54

```python
from topologicpy.Topology import Topology
from topologicpy.Wire import Wire

w = Wire.Rectangle()
Topology.ExportToJSON(w, path=r'D:\Desktop\1.json', overwrite=True)
w = Topology.ByJSONPath(path=r'D:\Desktop\1.json')
print(w)
``` 
in PyCharm:
![image](https://github.com/wassimj/topologicpy/assets/86838581/0a54aa52-e826-47f4-ab39-251b86a920ea)
in Jupyter notebook:
![Uploading image.png…]()

**Comment by wassimj** [comment]
oh! Seems like a multiprocessing issue! This will be difficult to debug because it works fine on my computer.
<img width="767" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/ca47d3ce-1469-4eca-9799-beb11d1268d5">

**Comment by wassimj** [comment]
@gaoxipeng ... Can you please send me the breps of the building to test time? I wonder why it is taking 30 minutes. How many cells and faces does it have? 10,000 faces is usually about 3-4 minutes

**Comment by gaoxipeng** [comment]
1. Yes, running Jupyter notebook on my PC has the same results as yours, but it will output the 0/0 line and get the correct result. In Pycharm, it will report an error and stop running, which may have been normal in previous versions at 0.4.36

2. The efficiency of the current version (Topology. Show()) is acceptable. I uploaded a previous Brep file for testing.

```python
from topologicpy.Topology import Topology

cluster = Topology.ByBREPPath(path=r'D:\Desktop\2.brep')
print(cluster)

import time

start_time = time.time()

Topology.Show(cluster, renderer='offline')

end_time = time.time()

execution_time = end_time - start_time

print(f"execution_time：{execution_time}s")
``` 
[20231110test.zip](https://github.com/wassimj/topologicpy/files/13319016/20231110test.zip)


The method for generating this Brep is to create cells using faces, create faces using lines representing doors and windows, generate two clusters, then use Topology. Difference (roomcells, win and door cluster), and finally use CellComplex. ByCells()
This also requires a significant amount of computation time, which is acceptable, possibly due to the need to check whether the faces intersect one by one


3. In version 0.4.54，Wire. BoundingRectangle() seems to be a problem, and in this test, there is a probability that an error will occur (perhaps it will take more than 10 runs to occur)

```python
from topologicpy.Wire import Wire
from topologicpy.Topology import Topology

w = Topology.ByBREPPath(r'D:\Desktop\1.brep')
print(w)
a = Wire.BoundingRectangle(w)
print(a)
``` 
![image](https://github.com/wassimj/topologicpy/assets/86838581/109447d7-362c-4801-b925-fd41b428d3ab)

**Comment by gaoxipeng** [comment]
Sorry to bother you again, in the latest version 0.4.56,There are a few small issues：
```python
from topologicpy.Face import Face
from topologicpy.Cell import Cell
from topologicpy.Cluster import Cluster
from topologicpy.Topology import Topology

f1 = Face.Star()
roof1 = Cell.Roof(f1)

f2 = Topology.Translate(f1, z=1)
roof2 = Cell.Roof(f2)
cluster = Cluster.ByTopologies([roof1, roof2])

Topology.Show(cluster)
``` 

Expect to receive：
![image](https://github.com/wassimj/topologicpy/assets/86838581/ebba635e-3a03-479b-afad-44980eeba578)
However, in this version, it is not possible to accurately represent concave shapes
![image](https://github.com/wassimj/topologicpy/assets/86838581/843c407d-45b0-44d7-b696-af514f546ecb)

in Cell.py line 1540，Espilon=epsilon is a typo，and Shell.Roof() unable to correctly move processed graphics to their original position.Looking forward to your repair.

**Comment by wassimj** [comment]
Regarding the wrong visualisation. Yes, known recently introduced bug. Solved internally. Will be fixed with next release in a few weeks.
Regarding typo. Will check and fix. Thanks for catching these

**Comment by wassimj** [comment]
Hello @gaoxipeng I believe I have fixed these errors in the newly released version 0.4.57. Can you please install and test and let me know? Thank you again for uncovering these bugs.

**Comment by wassimj** [comment]
By the way, in the new version you no longer need to cluster topologies before using Topology.Show. Instead you can use something like  Topology.Show(roof1, roof2, roof3, roof4)

**Comment by gaoxipeng** [comment]
Hello, I have tested the following code:
```python
from topologicpy.Topology import Topology
from topologicpy.Shell import Shell
from topologicpy.Cell import Cell
from topologicpy.Face import Face
from topologicpy.Edge import Edge
from topologicpy.Vertex import Vertex

v1 = Vertex.ByCoordinates(0, 0, 0)
v2 = Vertex.ByCoordinates(0, 1000, 0)
v3 = Vertex.ByCoordinates(200, 1000, 0)
v4 = Vertex.ByCoordinates(200, 1200, 0)
v5 = Vertex.ByCoordinates(400, 1200, 0)
v6 = Vertex.ByCoordinates(400, 1000, 0)
v7 = Vertex.ByCoordinates(800, 1000, 0)
v8 = Vertex.ByCoordinates(800, 1200, 0)
v9 = Vertex.ByCoordinates(1000, 1200, 0)
v10 = Vertex.ByCoordinates(1000, 1000, 0)
v11 = Vertex.ByCoordinates(1200, 1000, 0)
v12 = Vertex.ByCoordinates(1200, 0, 0)

vertices = [v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12]
edges = []

for i in range(len(vertices) - 1):
    edges.append(Edge.ByVertices([vertices[i], vertices[i + 1]]))
edges.append(Edge.ByVertices([vertices[-1], vertices[0]]))
face = Face.ByEdges(edges)
face = Face.Invert(face)

roof = Shell.Roof(face, degree=15)
print(roof)
Topology.Show(roof, renderer='offline', faceColor='red')
``` 
![image](https://github.com/wassimj/topologicpy/assets/86838581/27690df1-5983-47bd-81a1-1a3f9fb0e877)
![image](https://github.com/wassimj/topologicpy/assets/86838581/222564ed-d092-4ada-bf91-146c7d20da90)
![image](https://github.com/wassimj/topologicpy/assets/86838581/687ddcc3-6a3e-4d7d-a023-40f2b9529dc2)
Sometimes the roof can be created correctly, but it cannot be displayed correctly, so I think the problem lies in Face.ByWire, there is also a chance that this function will encounter problems in other tests. What changes have been made to this function compared to before? Do I need to ensure that the input edges are connected end-to-end?

**Comment by wassimj** [comment]
Dear @gaoxipeng I have just published 0.4.58 which should solve the above issue. The issue is in the display of degenerate wires. You will still get errors and warnings (I made topologicpy far more verbose than before. These are not new errors, but now they are being reported back to the user). However, the roof is correct and has the correct number of faces (10).
![newplot (9)](https://github.com/wassimj/topologicpy/assets/6302909/5c7395c1-4973-4da4-a2cb-bca7a6ac68b0)

**Comment by gaoxipeng** [comment]
Hello, there are still some special cases where errors are displayed. Hope they can be fixed，Thank you.

```python
from topologicpy.Topology import Topology

f = Topology.ByBREPPath(r'D:\Desktop\0112f.brep')
print(f)
Topology.Show(f, faceColor='red')
``` 
[0112f.zip](https://github.com/wassimj/topologicpy/files/13919689/0112f.zip)

**Comment by gaoxipeng** [comment]
I uploaded a simple graphic that could cause problems
[0113f.zip](https://github.com/wassimj/topologicpy/files/13919927/0113f.zip)

**Comment by wassimj** [comment]
Thank you @gaoxipeng for uncovering these edge cases. I believe this has been fixed in version 0.4.59. Please test and reply here to verify. Many thanks.
![zigzag](https://github.com/wassimj/topologicpy/assets/6302909/5e6ced23-05f7-4f9a-8299-70b85b7a5691)

**Comment by gaoxipeng** [comment]
Hello, this part of the code below will only display two verteies and not the edges,Looking forward to your repair
```python
from topologicpy.Vertex import Vertex
from topologicpy.Edge import Edge
from topologicpy.Topology import Topology

v1 = Vertex.ByCoordinates(0, 0, 0)
v2 = Vertex.ByCoordinates(10, 10, 10)
e = Edge.ByStartVertexEndVertex(v1, v2)
Topology.Show(e)
```

**Comment by wassimj** [comment]
Please first acknowledge and confirm that previous issues you raised have been solved. I usually reply with “Thank you this has been fixed”. It is only polite to do so

**Comment by gaoxipeng** [comment]
I'm so sorry, the previous issues have been solved. Thank you for your patience and dedication all the time, and apologize again for my impolite.

**Comment by wassimj** [comment]
@gaoxipeng No problem. Thank you for your rigorous testing. I believe I have now fixed this issue (as well as displaying a single vertex) in version 0.4.61 which has been published. Please let me know. Thanks again.

**Comment by gaoxipeng** [comment]
The issue has been solved,Thank you.

**Comment by wassimj** [comment]
Excellent! 🙂 Thank you.

**Comment by gaoxipeng** [comment]
Dear @wassimj ,I attempted to visualize a previous cellcomplex, The CellComplex is created by forming faces from edges similar to those in the image. Then, cells are created using Cell.ByThickenedFace, and finally, duplicate faces are removed using Topology.SelfMerge. but if showFaces=True, it doesn't display. I filtered out faces that might cause errors, yet this face also fails to display. This issue might be due to the face containing five vertices, among which two are close to each other. I tried using Face.RemoveCollinearEdges() on this face, and the function yielded the correct result. However, when I attempted to use Topology.RemoveCollinearEdges() on the CellComplex, it failed. Is there any method to obtain clean data? Thanks a lot😊.
![image](https://github.com/wassimj/topologicpy/assets/86838581/27b615a5-025a-4f4e-893a-9b6126442707)
[0119.zip](https://github.com/wassimj/topologicpy/files/13985812/0119.zip)
```python
from topologicpy.Topology import Topology

cp = Topology.ByBREPPath(r'D:\Desktop\aCellComplex.brep')
print(cp)
Topology.Show(cp,showFaces=False,renderer='offline')
cp = Topology.RemoveCollinearEdges(cp)
print(cp)
```

**Comment by wassimj** [comment]
Dear @gaoxping,
In your BREP cellComplex, I found 11 faces that are problematic. Mainly, when topologic asks for their external boundary and then tries to remove collinear edges, it is returning None. If I don't remove collinear edges, the faces cause a crash. When I displayed the faces, they appeared to be degenerate slivers (almost like an edge rather than a face). By ignoring these faces and using the valid ones, I was able to cluster them and display them properly. It seems CellComplex was lenient in accepting these faces, but I couldn't re-build a new cellComplex using the remaining valid faces (which is expected).

Try this code:

```
import sys
sys.path.append(r'C:\Users\sarwj\OneDrive - Cardiff University\Documents\GitHub')

from topologicpy.Topology import Topology
from topologicpy.Face import Face
from topologicpy.Wire import Wire
from topologicpy.CellComplex import CellComplex
from topologicpy.Cluster import Cluster
import topologic

cp = Topology.ByBREPPath("C:/Users/sarwj/Downloads/0119/aCellComplex.brep")
faces = Topology.Faces(cp)
new_faces = []
for i, f in enumerate(faces):
    eb = Face.ExternalBoundary(f)
    eb = Topology.RemoveCollinearEdges(eb)
    if not eb == None:
        ibList = Face.InternalBoundaries(f)
        ibList = [Wire.RemoveCollinearEdges(ib) for ib in ibList]
        ibList = [ib for ib in ibList if not ib == None]
        new_f = Face.ByWires(eb, ibList)
        if isinstance(new_f, topologic.Face):
            new_faces.append(new_f)
        else:
            print(i, "Found an invalid face:", f)
    else:
        print(i, "Found an invalid wire:", eb)

print("Original Faces", len(faces))
print("New Faces", len(new_faces))
cluster = Cluster.ByTopologies(new_faces)
print(cluster)
Topology.Show(cluster, renderer="offline")

```

![newplot (10)](https://github.com/wassimj/topologicpy/assets/6302909/4c5ccbf2-a530-4be7-a1bd-388015caf45b)

**Comment by gaoxipeng** [comment]
It is indeed a clever display method. I will add this part of the code before displaying it. I guess this might be due to the layers in my original data not being strictly aligned, which still falls under a precision issue. Thank you for your testing and reply😊.

**Comment by wassimj** [comment]
I have added this code to version 0.4.62 so you don't have to add it yourself. Please wait for a few minutes and download 0.4.62. Kindly report back here if this issue is now solved. Thanks as always for testing :)

**Comment by wassimj** [comment]
version 0.4.62 has now been published.

**Comment by gaoxipeng** [comment]
Thank you for your modification, the display issue has been resolved👍. There are some minor issues. In Plotly.py line 840, 'p = Topology.ByBREPPath("C:/Users/sarwj/Downloads/0119/aCellComplex.brep")' should be commented out. Also, I am not sure if pyvis should be added to the dependency list to be installed along with topologicpy. If 'from topologicpy.Graph import Graph' is used, it will install some files in the directory of the py file, which I think should be in the same directory as topologicpy.

**Comment by wassimj** [comment]
Ah thanks! The dangers of rushing! I will remove tomorrow. Yes, I think I need to add a few more dependencies. Thanks

**Comment by wassimj** [comment]
@gaoxipeng Hello! I just published version 0.4.63 which I hope solves the dependencies issues and the installation of 3rd party libraries. I changed the way they are installed so that they go to the standard site-packages folder either at the system level if the user has root access or at the user level if they don't. I also added most of the needed libraries to the dependencies list (except torch and dgl because they require special installation ahead of time based on hardware configuration). If possible, please check and give me feedback if the new code is working better than before and/or if there are any bugs or issues. Many thanks!

**Comment by gaoxipeng** [comment]
Dear @wassimj , I encounter the error "No stream support: No module named 'lark'" when I only use pip install topologicpy in a virtual environment, and solely utilize from topologicpy.Graph import Graph. the version is 0.4.64, I hope this information is helpful to you.
![image](https://github.com/wassimj/topologicpy/assets/86838581/b5db5629-bcbe-4c68-9d31-125ec5f21277)

**Comment by wassimj** [comment]
Yes, I see this error as well. Please try version 0.4.65 which includes lark as a dependency. Does it solve it? Thank you.

**Comment by gaoxipeng** [comment]
Yes, there is no problem with the current dependency😁,Regarding the previous multithreading issue, I tried providing the error message to GPT and obtained some potentially helpful information.
Code that caused the error:
```python
from topologicpy.Topology import Topology
from topologicpy.Wire import Wire

w = Wire.Rectangle()
Topology.ExportToJSON(w, path=r'D:\Desktop\0122.json', overwrite=True)
w = Topology.ByJSONPath(path=r'D:\Desktop\0122.json')
print(w)
``` 
![image](https://github.com/wassimj/topologicpy/assets/86838581/9335f4bf-93f7-4717-9dc5-a451cdc1e21d)
Correct usage method:
```python
from topologicpy.Topology import Topology

if __name__ == "__main__":
    w = Topology.ByJSONPath(r'D:\Desktop\0122.json')
    print(w)

``` 
![image](https://github.com/wassimj/topologicpy/assets/86838581/1b1c8582-a0e8-40c3-8e78-853d8dec7a6c)
![image](https://github.com/wassimj/topologicpy/assets/86838581/a15e2560-0a9b-4f8a-bbfb-7dba370fd3a4)
This may only be a problem on my computer,Brep can also be used as an alternative, and it seems that using Json takes a longer time

**Comment by wassimj** [comment]
Dear @gaoxipeng, This error only happens if you are running from the python console rather than from jupyter notebook or other environments. If that is the case, then you are correct, the proper idiom is to use the if __name__ == '__main__': before you call functions that use multi-processing. On my mini-pc, it takes 2.23 seconds to write out the Wire.Rectangle to sa JSON file and read it back in. Obviously, there is a lot of overhead when you are writing such a simple geometry to JSON, but you are correct, JSON is a slow format. This has been discussed widely online. It is a powerful and rich format, but slow. In comparison, writing out to a BREP file and to an OBJ file and reading it back in took only 0.02 seconds for each format so 100x faster!

**Comment by gaoxipeng** [comment]
Dear @wassimj ，Thank you for your patient explanation. I have tested Jupyter and it indeed works correctly👍. All my doubts have been resolved. Thank you again for your long-term patience in guidance and timely repairs🫡.

**Comment by gaoxipeng** [comment]
Dear @wassimj ，In version 0.7.86, in lines 656 and 683 of Plotly.py, name=label should be changed to name=legendLabel to correctly display the labels for points and edges. Looking forward to your testing and response.
