### ISSUE TITLE
Topology.Show() does not colorize surfaces  if vertices are turned off.

### ISSUE THREAD

**Issue by nickger** [wassimj/topologicpy#41]
Topology.Show() ignores color of surfaces if showVertices is False. Tried in Jupiter Lab:
![image](https://github.com/wassimj/topologicpy/assets/74200801/4e7bf0b7-c77c-4106-9126-ea9ac0959207)

And with vertices:
![image](https://github.com/wassimj/topologicpy/assets/74200801/cc05e4cc-a9e8-4092-9262-6d36d5295343)

**Comment by wassimj** [comment]
Yes, sorry about that. This bug has been solved in the code, but a new version has not been published. If you need it immediately, please download the Plotly.py file from github and replace the one that has been installed as part of the topologicpy package.

**Comment by nickger** [comment]
Well, this is not the only issue with Show... Mostly, when I try to visualize Cells it returns errors. Try the attached example, please, may be I am wrong...
[visual_failure.json](https://github.com/wassimj/topologicpy/files/13523847/visual_failure.json)

**Comment by wassimj** [comment]
Hi @nickger ... I need more specific information and if possible visual results (images as you did above) to see what the issue is.

**Comment by wassimj** [comment]
Hi @nickger ... Can you send me a BREP rather than the JSON file. There is a bug in the JSON file which has also been corrected (basically we moved from a mantissa=4 to mantissa=6 to increase resolution as it was not able to rebuild edges with only 4 decimal points).

**Comment by nickger** [comment]
Sure.
The Brep is attached (remove txt extension). The Show failure s following:
![image](https://github.com/wassimj/topologicpy/assets/74200801/48937b3e-742f-439b-9eb7-7d69307a7e1c)
[visual_failure.brep.txt](https://github.com/wassimj/topologicpy/files/13525867/visual_failure.brep.txt)

**Comment by wassimj** [comment]
Hi @nickger .. The error happens earlier than Plotly. Basically, when I try to import the BREP file, I am getting "None" back. Not sure why as CAD Assistant does display it. However, once i converted it to .OBJ and imported into topologicpy, it worked but still gave errors. Something fishy with the geometry.
<img width="890" alt="error" src="https://github.com/wassimj/topologicpy/assets/6302909/204496d9-24ea-4253-8c85-b63a9fbf94c8">

**Comment by nickger** [comment]
I am still fighting, but one bug is clear: line 828 in Plotly.py uses Triangulation, which (in my case at least) returns a list(!) of shells with one shell in the list This is incompatible with line 833, where one more triangulation is applied directly to the list. Although it is clear, that a good face being triangulated must return at most one shell, an additional proof and fix is preferable.
Meanwhile I check the triangulation itself...

**Comment by wassimj** [comment]
Thank you! I will look at that code and make it more robust through checking return values

**Comment by nickger** [comment]
Got it. Line 6477 in Topology.py - Triangulation - uses Shell.ByFaces() and returns it directly, although line 263 in Shell.py - ByFaces - allows it (obviously) to be a list. 
Moreover, if line 261 returns Shell - it is lost according to line 267!
I would say, it is not optimal to use methods, which require tolerance to be executed correctly, inside other methods, without specific tolerance, like Show().
Or, if we use it, change the usage of these nested methods to dynamic tolerance , say, some iterations till the method returns desired value or type.
Another optimism in line 741 in Plotly.py - suggestion that all faces are all good. After so much manipulation they are not...
And one more thing: I would suggest using .Copy() of input data in Show() even if it doubles memory usage. Geometrical manipulations with input data may cause their corruption as I have already experienced with mixed usage of python and original topologic types...

**Comment by wassimj** [comment]
@nickger 
I have completed many updates over the weekend and uploaded to github. I am not ready to publish to pip until more testing is done. However, if you know what you are doing, you can download the files and build your own experimental version of topologicpy. If things go wrong, just revert to the pip installable version or a saved version.

1. You are correct about tolerance not being propagated through the methods. I have made a big push on this. Now, many methods have an added optional tolerance input that propagates to the called functions that need it. 
2. I decided that Triangulations should not return a list. I simply make it fail if it cannot create a proper shell. It is best that the user fixes their face before triangulation.
3. I fixed the plotly stuff. But needs testing and proof it works. Would love to hear back that it works.
4. I am against using Topology.Copy(). If you can show me where the data is being corrupted, I can debug, but making copies is not a good approach. Original topologies should not be modified unless you intentionally modify them.
Thanks
