### ISSUE TITLE
RemoveCoplanarFaces works not complitely

### ISSUE THREAD

**Issue by nickger** [wassimj/topologicpy#42]
The geometry is attached. Please, have a look.
[coplanar_failure.brep.txt](https://github.com/wassimj/topologicpy/files/13561183/coplanar_failure.brep.txt)
The method Topology.RemoveCoplanarFaces() leaves  coplanar faces unmerged. What I've noticed:
- Topology.py lines 4639 and 4640 duplicate each other, lines 4621 and 4627 also
- Topology.py line 4630 uses Shell.ByFaces() which is wacky, please check if all cases covered
[coplanar_failure2.brep.txt](https://github.com/wassimj/topologicpy/files/13561607/coplanar_failure2.brep.txt)

What I expect to be enough to get final faces:
clusters = Topology.ClusterFaces(topology, tolerance=tolerance)
        faces = []
        for aCluster in clusters:
            aCluster = Topology.SelfMerge(aCluster)
            if isinstance(aCluster, Face):
                faces.append(aCluster)
            elif isinstance(aCluster, topologic.Shell):
                shells = [aCluster]
            else:
                shells = Cluster.Shells(aCluster)
           for shell in shells:
               faces.append(Face.ByShell(shell))

If this doesn't work, all these workarounds with constructors - deconstructors don't make sense. I suppose, SelfMerge() (which relies on original c++ SelfMerge) is too implicit method, though the shortest to dissolve features. As soon as we know, that aCluster is always a cluster of faces, here could be an explicit algorithm to find adjacent faces and dissolve common edges.

**Comment by wassimj** [comment]
@nickger Can you please book a time to meet with me as I am finding it hard to understand what you are encountering. I need to make sure that this is not an edge case or you are suggesting something that works only for your workflow. For that, I need to have a discussion with you. Please book using http://jabiw.ycb.me   Thanks

**Comment by wassimj** [comment]
@nickger You are also welcome to improve the algorithm, test it and submit a pull request.

**Comment by wassimj** [comment]
Dear @nickger,
I have simplified and improved Topology.RemoveCoplanarFaces and uploaded the files to github. However, it is still not 100% and it fails on your second test. It cleans up most of the faces, but some get corrupted. I tried different angular tolerances and scalar tolerances to no avail. Not sure what is going on. So, I am still not ready to pip release a new version of topologicpy, but these fixes will be included in the next release (or, as before, your can download the changed files and build your own).
<img width="613" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/b89524d9-0d0f-42e4-bc81-b1b6dac77624">
<img width="341" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/8d66f953-94f0-420e-9994-1d9bd1d02e4c">
<img width="346" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/d42d379c-5a17-4bf4-8fba-2a069e98b9b3">
<img width="313" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/d74193b3-f0a8-497f-b86f-1f5498119ae0">
<img width="305" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/9cb20b86-e087-4647-8680-fe1528d12e7b">

<img width="310" alt="image" src="https://github.com/wassimj/topologicpy/assets/6302909/de19694e-32f8-4491-9569-c1320dbec2dc">

**Comment by nickger** [comment]
Thank you for the rush answer, I do appreciate that, because I am very limited in time for tests. The task itself is not so urgent, but it stopes me on my basic goal - to process "real" geometries from meshes. I understand, it is not the original purpose of the package, but would be great...
