### ISSUE TITLE
Face.ByShell() returns list of faces if it cannot create a single face

### ISSUE THREAD

**Issue by nickger** [wassimj/topologicpy#45]
There is an inconsistency in results for constructors: Shell.ByFaces() returns None if creation fails (expected behaviour), whereas Face.ByShell() return list of faces if creation of a single face fails. May be there are more, haven't checked all constructors...
Is there a chance to implement OpenCascade CellBuilder with option to remove inner boundaries? This would solve soo many problems...

**Comment by wassimj** [comment]
Shell.ByFaces was modified based on your suggestion. I’m not a purist. The return values are needed in edge cases and returning None when you could return something useful is not my preferred option. The C++ code is frozen for now but you can always branch it and implement modifications as you wish.
