### ISSUE TITLE
Wire.Planarize and and error forming a face

### ISSUE THREAD

**Issue by martinvrielink** [wassimj/topologicpy#49]
Hi Wassim,
I have studies the following BREP shape consisting of Wires:
![image](https://github.com/wassimj/topologicpy/assets/167056277/bb75fb80-c8fe-4e6e-adc6-fa070db53754)
The goal is tho go to a cell which later can be used. I did not have success thusfar.

Side note:
Thinking the cause of not being able to form a cell might be that the Wires are not planar I went ahead using 
```
pwires =[]
for i in wires:
    pnwire = Wire.Planarize(i)
    pwires.append(pnwire)
```
Here the controid of the plane did not read correctly as default.
![image](https://github.com/wassimj/topologicpy/assets/167056277/68afe0b4-3978-453b-9a7e-9c299621a59a)

So I used: 
`    ctrd = Topology.Centroid(i)
pnwire = Wire.Planarize(i,ctrd)`

The cell is not formed because Face/Wire on index 6 is forming an incorrect face. It is not using the outer edges (in red):
Maybe because the centre point of the face in not on the face?
![12](https://github.com/wassimj/topologicpy/assets/167056277/733a802e-3159-4f4c-864c-34c72e93cb7d)

Does this face need to be triangulated before going into Topologicpy or can Topologicpy handle this exception?

Kind regards, Martin Vrielink

BREPS:
[RevitJoinedMassWires.zip](https://github.com/wassimj/topologicpy/files/14974969/RevitJoinedMassWires.zip)
Notebook:
[Situation 02 - Face triangulate.zip](https://github.com/wassimj/topologicpy/files/14974978/Situation.02.-.Face.triangulate.zip)

**Comment by martinvrielink** [comment]
Hi Wassim,
I found a similar face as the previous which could not form a face:
![image](https://github.com/wassimj/topologicpy/assets/167056277/243f1477-0556-4b2f-8e9d-4c2c5773608e)
See:
[Brep and notebook.zip](https://github.com/wassimj/topologicpy/files/15033335/Brep.and.notebook.zip)
Kind regards, Martin

**Comment by wassimj** [comment]
@martinvrielink Let me know if this is still an issue. Closing for now.
