### ISSUE TITLE
Wire not forming face.

### ISSUE THREAD

**Issue by martinvrielink** [wassimj/topologicpy#50]
Hi Wassim,
The last issue was solved by updating to the latest version of topologicpy.
However I found another face which could not form a face:
![image](https://github.com/wassimj/topologicpy/assets/167056277/243f1477-0556-4b2f-8e9d-4c2c5773608e)
See:
[Brep and notebook.zip](https://github.com/wassimj/topologicpy/files/15033335/Brep.and.notebook.zip)
Am i missing something or is this an issue?
PS: the Wire.Planarize does noet get the centroid by default in
`wireplanar = Wire.Planarize(wire)` 
Kind regards, Martin

**Comment by wassimj** [comment]
Hi @martinvrielink was this last issue resolved? What was the issue and how was it resolved? Thanks!

**Comment by martinvrielink** [comment]
Hi Wassim,
By checking if the centre point of the surface is on te surface, and if not, triangulating the face before going to Topologicpy resolved on specific situation. However this is not always working and not the preferred way to go. I reopened [https://github.com/wassimj/topologicpy/issues/49](url)

**Comment by wassimj** [comment]
Ok. When I get back, I will examine the code and try to make it more robust to check for various conditions.

**Comment by wassimj** [comment]
Hi @martinvrielink .. Is this still an issue? If so, please re-open this issue.
