### ISSUE TITLE
Topology.ExportToJSON is not working in version 0.7.5

### ISSUE THREAD

**Issue by newshunhk** [wassimj/topologicpy#55]
Hi,

I try to export a cellcomplex to a json file. However it gives me this warning:
![image](https://github.com/wassimj/topologicpy/assets/170861726/0b7fb401-adb5-4d72-9fab-9fbf7e9c5cfd)

Then I downgrade the topologicpy back to 0.7.0 and it works.
![image](https://github.com/wassimj/topologicpy/assets/170861726/6bff7d87-f765-4552-8c4b-c5725700c363)

**Comment by wassimj** [comment]
Can you send me the jupyter notebook that is causing this crash? Also, I just want to note that "cell" in the error above, refers to a jupyter notebook cell, not a topologic Cell.

**Comment by newshunhk** [comment]
here is the file
[ExportJson.zip](https://github.com/wassimj/topologicpy/files/15447271/ExportJson.zip)

**Comment by wassimj** [comment]
@newshunhk  I just tested it and it exported with no warnings. I am closing this for now, but if this is still an issue with the latest version of topologicpy, please feel free to re-open the issue.
