### ISSUE TITLE
Memory corrupt error in 7.15

### ISSUE THREAD

**Issue by martinvrielink** [wassimj/topologicpy#59]
Hi Wassim,

By updating to topologicpy 7.15 i encountered a "memory error" error in dynamo. This error accurs after getting a list of faces and then using Topology.Geometry. I do this to reconstruct the faces in Dynamo:
![Schermafbeelding 2024-06-12 093354](https://github.com/wassimj/topologicpy/assets/167056277/a28460f5-dd27-4724-b9c0-d56a68279d6c)

I went ahead to recreating this issue in jupyter notebook to see if i could find out where the error comes from. Thus far I can get the vertices from the faces. But as soon I ask for the Face.Wire or Topology.Geometry the script crashes.
![Schermafbeelding 2024-06-12 094910](https://github.com/wassimj/topologicpy/assets/167056277/27e50ebb-129b-4ad9-b15e-3eb626a24d12)

I have attached the BREPS and notebook. 
[Situation 07 - Face memory error.zip](https://github.com/user-attachments/files/15800669/Situation.07.-.Face.memory.error.zip)

Kind regards,

Martin Vrielink

**Comment by wassimj** [comment]
Dear @martinvrielink,
I believe I have fixed this in version 0.7.18. Can you please test and report back? Please note that the method Face.NormalAtParameters and Face.NormalAsEdgeAtParameters have been removed since topologicpy only deals with planar faces. As such, always use Face.Normal(aFace, outputType="xyz", mantissa=6)

**Comment by wassimj** [comment]
Also, when doing Topology.Geometry. It is recommended that you first Triangulate the topology before outputing to geometry. Many other 3D modelling software assume a mesh made of triangles.

**Comment by wassimj** [comment]
I am closing this issue since I have not heard back from you.
