### ISSUE TITLE
Importing IFC with IfcShapeAspects 

### ISSUE THREAD

**Issue by nickger** [wassimj/topologicpy#68]
I suggest that the newest function is ByIFCFile line 2340 in Topologic.py.
Here you filter IFC file by IfcProducts subclasses and for each valid class instance you return a "Topology" object of type "CellComplex" generated by function "convert_to_topology".
First of all IfcShapeAspect is not a subclass of IfcProduct. Moreover, ProductDefinitionShape is NOT AWARE that it actually has ShapeAspects, it is stored vice versa, instances of IfcShapeAspects refer to DefinitionShape. Look at this fragment where a wall consists of 2 parts with different materials:

#125=IFCSHAPEREPRESENTATION(#101,'Axis','Curve3D',(#124));
#126=IFCPRODUCTDEFINITIONSHAPE($,$,(#125,#148));
#127=IFCWALL('2RkyllETjCDQGE6WF558uw',#18,'Basic Wall:Wall 2:3000',$,'Basic Wall:Wall 2',#122,#126,'3000',.NOTDEFINED.);
#128=IFCCARTESIANPOINTLIST2D(((-50.000000000000767,-1320.0000000000002),(49.99999999999924,-1320.0000000000002),(50.000000000000767,1320.0000000000002),(-49.99999999999924,1320.0000000000005),(-50.000000000000767,-1320.0000000000002)));
#129=IFCINDEXEDPOLYCURVE(#128,$,.F.);
#130=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,'Wall 2',#129);
#131=IFCCARTESIANPOINT((1320.,100.,0.));
#132=IFCAXIS2PLACEMENT3D(#131,#9,#8);
#133=IFCEXTRUDEDAREASOLID(#130,#132,#9,2999.9999999999995);
#134=IFCCARTESIANPOINTLIST2D(((-100.00000000000077,-1319.9999999999995),(99.999999999999247,-1319.9999999999995),(100.00000000000077,1320.0000000000005),(-99.999999999999247,1320.0000000000007),(-100.00000000000077,-1319.9999999999995)));
#135=IFCINDEXEDPOLYCURVE(#134,$,.F.);
#136=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,'Wall 2',#135);
#137=IFCCARTESIANPOINT((1320.,-50.,0.));
#138=IFCAXIS2PLACEMENT3D(#137,#9,#7);
#139=IFCEXTRUDEDAREASOLID(#136,#138,#9,2999.9999999999995);
#140=IFCCOLOURRGB($,0.49803921568627452,0.49803921568627452,0.49803921568627452);
#141=IFCSURFACESTYLERENDERING(#140,0.,$,$,$,$,IFCNORMALISEDRATIOMEASURE(0.5),IFCSPECULAREXPONENT(64.),.NOTDEFINED.);
#142=IFCSURFACESTYLE('Default Wall',.BOTH.,(#141));
#143=IFCSTYLEDITEM(#133,(#142),$);
#144=IFCCOLOURRGB($,0.,0.,1.);
#145=IFCSURFACESTYLERENDERING(#144,0.75,$,$,$,$,IFCNORMALISEDRATIOMEASURE(0.5),IFCSPECULAREXPONENT(64.),.NOTDEFINED.);
#146=IFCSURFACESTYLE('Glass',.BOTH.,(#145));
#147=IFCSTYLEDITEM(#139,(#146),$);
#148=IFCSHAPEREPRESENTATION(#102,'Body','SweptSolid',(#133,#139));
#149=IFCSHAPEREPRESENTATION(#102,'Body','SweptSolid',(#133));
#150=IFCSHAPEASPECT((#149),'Default Wall',$,.U.,#126);
#151=IFCSHAPEREPRESENTATION(#102,'Body','SweptSolid',(#139));
#152=IFCSHAPEASPECT((#151),'Glass',$,.U.,#126);
#153=IFCMATERIAL('Default Wall',$,'Unassigned');
#154=IFCMATERIAL('Glass',$,'Unassigned');

ShapeAspects #152 and #150 both refer to DefinitionShapes #126 but not other way around, #126 refers to ShapeRepresentation for context "Body" which refers to 2 IfcExtrudedAreaSolids - this is what you get with property "shape.geometry". Obviously, this direct property loses information about particular primitives, i.e. you cannot find a primitive to write the material information into it.
The solution should be like this:
1. Collect information about IfcShapeAspects in the Ifc file: the ids of geometries they refer to, the ids of product representations they refer to and their materials
2.  Iterate through instances of selected classes and go one level deeper in geometry processing: find the representation for "body" context and iterate through its primitives
3. while iterating through primitives check whether their ids are in data from step 1 and populate their dictionaries accordingly
4. join resulting cells (in IFC a "body" primitive is always a cell in topological meaning) in a cell complex with its own dictionary.

Hope, it is what you are after.

P.S. I highly recommend to find a way to use pyhton_occ geometry parser and use that occ geometry in your topologicpy as soon as you also use occ in the backend. This will dramatically improve the performance for real Ifc.

**Comment by wassimj** [comment]
Thanks. You have some misconceptions about the code. I know full well that shape aspects are not subclasses of IfcProduct.
Anyway. Did you try the code and it didn’t work??

**Comment by nickger** [comment]
No, I didn't. I thought you don't know how to recognize  materials for aspects, if you managed - ok.

**Comment by wassimj** [comment]
It is ok. You don’t know me and you assumed I don’t know what I am talking about. But I have been writing software since 1988 and I am a Professor of Computational Methods and a book author. So no worries.
