### ISSUE TITLE
Topology.ExportToJSONMK1 error

### ISSUE THREAD

**Issue by Sinasta** [wassimj/topologicpy#7]
When using Topology.ExportToJSONMK1 function i get an error. I don't recall the exact error because i already did some changes in the function to solve that error. But if necessary i can check for the exact error.
The error is due to
https://github.com/wassimj/topologicpy/blob/e83aaaf05e9a76dae67fe1887806b0ec7e8e7e65/Topology.py#L2451
https://github.com/wassimj/topologicpy/blob/e83aaaf05e9a76dae67fe1887806b0ec7e8e7e65/Topology.py#L2472
https://github.com/wassimj/topologicpy/blob/e83aaaf05e9a76dae67fe1887806b0ec7e8e7e65/Topology.py#L2493
https://github.com/wassimj/topologicpy/blob/e83aaaf05e9a76dae67fe1887806b0ec7e8e7e65/Topology.py#L2514
https://github.com/wassimj/topologicpy/blob/e83aaaf05e9a76dae67fe1887806b0ec7e8e7e65/Topology.py#L2525
https://github.com/wassimj/topologicpy/blob/e83aaaf05e9a76dae67fe1887806b0ec7e8e7e65/Topology.py#L2541
those variables not being Python dictionaries but topologic dictionaries.
Which causes the `topologicdict.keys()` lines to throw an error.
Furthermore the json serialization fails with topologic dicts.
My fix is to convert each of the aforementioned topologic dicts into python dicts with: `Dictionary.PythonDictionary()`
If anybody can verify that it is not only me who is having that error, i am happy to propose a PR.

**Comment by Sinasta** [comment]
The same goes for `Topology.ExportToJSONMK2()`

**Comment by wassimj** [comment]
@Sinasta I believe this has been fixed for Topology.ExportToJSONMK1 (but not MK2 yet) in version 0.2.4. Please test and report back here so I can close this issue if fixed. Thank you.

**Comment by Sinasta** [comment]
It seems that your fixes do solve the issue.
