### ISSUE TITLE
I can help publish topologigcpy and topologic on conda-forge

### ISSUE THREAD

**Issue by Krande** [wassimj/topologicpy#71]
Hello @wassimj, I recently started exploring topologicpy and topologic and found the concepts of using non-manifold cell complexes as a modelling scaffold quite interesting and fun to work with!

With your permission I'd like to help publish both packages on conda-forge (which is where most of my own packages are published. Fyi. I am also responsible for maintaining the ifcopenshell conda-forge package). 
I have already made and tested building conda-recipes for both topologic and topologicpy, so with your blessing, I'll start the process of setting up the conda-forge publishing pipelines for topologic and topologicpy. 

FYI: I noticed you rely on submodules in topologic for including pybind11. For conda-forge relying on submodules isn't ideal, so I made a patch for `TopologicPythonBindings/CMakeLists.txt`. If you'd like me to make a PR to topologic with a fix that allows passing in a flag to switch between "conda" and "git" for pybind11, just let me know. 

Let me know what you think,

Best Regards
Kristoffer

**Comment by wassimj** [comment]
Hi @Krande, thanks for your enthusiasm for topologic and topologicpy. Yes, please go ahead with the conda-forge integration. I am not familiar with these types of pipelines. When you make the PR for topologic, also please include detailed instructions for the README file as well. Kindly modify it as needed to make sure everyone understand how to build it for git and for conda. Many thanks!
