### ISSUE TITLE
Issue with Topology.RemoveCoplanarFaces() on walls with holes

### ISSUE THREAD

**Issue by bigknutschi** [wassimj/topologicpy#76]
Hi Wassim!

First off, I want to say how much I’m enjoying working with TopologicPy—great work on this library!

I’ve come across what seems to be an issue with the method Topology.RemoveCoplanarFaces(). I’m currently using TopologicPy to create a Topologic model from an IFC file and save it in Neo4j.

The problem arises with triangulated walls that contain holes—they cannot be polygonated. To help illustrate the issue, I’ve prepared a minimal example that reproduces the behavior.

Looking forward to your thoughts on this!

Best regards,
Max

`# CreateBrepCube
from topologicpy.Face import Face
from topologicpy.Topology import Topology
from topologicpy.Vertex import Vertex
from topologicpy.Cell import Cell

wall_width = 5.0
wall_height = 3.0
hole_width = 2.0
hole_height = 1.0

wall_vertices = [
    Vertex.ByCoordinates(0, 0, 0),
    Vertex.ByCoordinates(wall_width, 0, 0),
    Vertex.ByCoordinates(wall_width, wall_height, 0),
    Vertex.ByCoordinates(0, wall_height, 0),
]

hole_offset_x = (wall_width - hole_width) / 2
hole_offset_y = (wall_height - hole_height) / 2

hole_vertices = [
    Vertex.ByCoordinates(hole_offset_x, hole_offset_y, 0),
    Vertex.ByCoordinates(hole_offset_x + hole_width, hole_offset_y, 0),
    Vertex.ByCoordinates(hole_offset_x + hole_width, hole_offset_y + hole_height, 0),
    Vertex.ByCoordinates(hole_offset_x, hole_offset_y + hole_height, 0),
]

wall_face = Face.ByVertices(wall_vertices)
hole_face = Face.ByVertices(hole_vertices)
face_with_hole = Topology.Boolean(wall_face, hole_face, operation="difference")
cell_with_hole = Cell.ByThickenedFace(face_with_hole, thickness=0.5)

Topology.Show(cell_with_hole)`

![image](https://github.com/user-attachments/assets/41e2c908-b8a8-4cc1-ac8a-04db2cb84897)

`tri_cell_with_hole = Topology.Triangulate(cell_with_hole)
Topology.Show(tri_cell_with_hole)`

![image](https://github.com/user-attachments/assets/3e673475-8106-4089-a668-607b4c1f216d)

`untri_cell_with_hole = Topology.RemoveCoplanarFaces(tri_cell_with_hole)
Topology.Show(untri_cell_with_hole)`

![image](https://github.com/user-attachments/assets/68606bc3-5fa6-4929-8e88-93f2e70a577d)

**Comment by wassimj** [comment]
Thank you for the bug report. As it happens, I had discovered it a day before (thanks to a report from a colleague over email) and was working on a fix when you submitted this issue :). I believe this is now solved in version 0.7.84. Please test and let me know by replying here and closing the issue if it is indeed solved. Thanks again for the bug report and kind words and let me know if you encounter any other issues.
![image](https://github.com/user-attachments/assets/76280f82-9753-4012-bcf6-d24f52da0d15)
![image](https://github.com/user-attachments/assets/114be872-1c2e-4552-b792-40b0a718ba67)
![image](https://github.com/user-attachments/assets/19dbc04b-4593-41b3-a6ae-9e67aafe958d)
![image](https://github.com/user-attachments/assets/17c681be-448a-4a14-b07f-3bd3555920c8)

**Comment by bigknutschi** [comment]
Solved!
