### ISSUE TITLE
Link to topologic.app doesn't work

### ISSUE THREAD

**Issue by Utopiah** [wassimj/topologicpy#77]
Trying to read a bit more on principles at https://topologic.app after the Design-Tech Talk presentation for PA Academy but getting a "Your PHP installation appears to be missing the MySQL extension which is required by WordPress." error.

**Comment by Utopiah** [comment]
FWIW https://topologic.app/topologicpy_doc/ does work.

**Comment by wassimj** [comment]
Thank you for pointing this out! I am getting the same error. I will investigate. I think some update messed things up. For now, please just use: http://pypi.org/project/topologicpy

**Comment by wassimj** [comment]
This has been solved.
